### ISSUE TITLE
warning or termination if too many missing frames are found

### ISSUE THREAD

**Issue by jpiesing** [cta-wave/device-observation-framework#10]
Given the ease with which QR codes may fail to be detected (at least on phones), it would be good if the framework would at least generate a warning if the number of missed frames goes above a certain threshold and/or have an argument to allow the user to specify that a run should terminate if the number of missed frames goes above a certain threshold.

**Comment by andyburras** [comment]
We could add a user-defined threshold to terminate a session if the number of missing frames on an individual test is greater. This would save the tester's elapsed time if e.g. an environment setup was poor so no test was going to run reasonably.

**Comment by jpiesing** [comment]
Please. Every run so far for me has 25% missing frames.

**Comment by yanj-github** [comment]
Hi @jpiesing Is there specific default value do you want please? If not I will put missing_frame_threshold = 50 for now.

**Comment by jpiesing** [comment]
> Hi @jpiesing Is there specific default value do you want please? If not I will put missing_frame_threshold = 50 for now.

That sounds good.

**Comment by jpiesing** [comment]
I'm confused about what is being measured to determine when to terminate.
Is it missing mezzanine frames (as determined by the frame number in the QR code)?
Is it frames from the camera where QR codes could not be successfully extracted?
I was expecting the 2nd of these but the documentation & terminology suggests it's the first.

**Comment by andyburras** [comment]
It's the first. The 2nd method doesn't work because we can get camera frames at any point in the recording that contain QR codes too faint to be decoded (which is why we record at at least twice the media frame rate). The problem is that the pixels don't appear and disappear instantly, they "fade up" to full brightness and then "fade down" to black.

**Comment by jpiesing** [comment]
> It's the first. The 2nd method doesn't work because we can get camera frames at any point in the recording that contain QR codes too faint to be decoded (which is why we record at at least twice the media frame rate). The problem is that the pixels don't appear and disappear instantly, they "fade up" to full brightness and then "fade down" to black.

It seems I wasn't clear enough.

It is **essential** for people using the test suite to be able to distinguish measurement setup bugs from implementation bugs. The person running the test needs to take different action in these two cases. **I cannot emphasize this requirement enough**. Please consider this paragraph to be in the equivalent of a 48-point gothic font, red, bold and flashing. 

If an implementation is dropping frames then there will likely be frames where a QR code can be extracted but the frame number is found to be a repetition of a previous one. 
A discontinuity in frame number following unexpected repetitions where QR codes could be extracted needs to be highlighted from a discontinuity following unexpected repetitions where no QR code could be extracted.

Please change the solution to this issue and highlight if **too many** frames are found where no QR code can be extracted.

**Comment by yanj-github** [comment]
@jpiesing Are you happy with the following logic please?

If within a test, too many **consecutive** camera frames are found where no QR code can be extracted then terminate the OF with a message to the user for the reason for termination, and suggesting that this may be due to a poorly setup camera environment.
We will make the threshold configurable so a user can choose to set to different threshold if it is required, with zero meaning do not do the check.
Can you suggest a default threshold value for this please? How about 10?

**Comment by jpiesing** [comment]
> If within a test, too many **consecutive** camera frames are found where no QR code can be extracted then terminate the OF with a message to the user for the reason for termination, and suggesting that this may be due to a poorly setup camera environment.

This is better than the current situation.
What about a multiple of the mezzanine frame rate so a number of consecutive mezzanine frames rather than a consecutive number of camera frames?

> We will make the threshold configurable so a user can choose to set to different threshold if it is required, with zero meaning do not do the check.
> Can you suggest a default threshold value for this please? How about 10?

What about 4 mezzanine frames?

**Comment by yanj-github** [comment]
> 
> 
> > If within a test, too many **consecutive** camera frames are found where no QR code can be extracted then terminate the OF with a message to the user for the reason for termination, and suggesting that this may be due to a poorly setup camera environment.
> 
> This is better than the current situation.
> What about a multiple of the mezzanine frame rate so a number of consecutive mezzanine frames rather than a consecutive number of camera frames?
> 
> > We will make the threshold configurable so a user can choose to set to different threshold if it is required, with zero meaning do not do the check.
> > Can you suggest a default threshold value for this please? How about 10?
> 
> What about 4 mezzanine frames?

I think this is better thanks @jpiesing 
Just make sure that I caculate this correctly do you mean this please?
4 mezzanine frames means 4*120/60fps = 8 and 4*120/15fps = 32
Where 120 is recording rate.

**Comment by jpiesing** [comment]
> I think this is better thanks @jpiesing
> Just make sure that I caculate this correctly do you mean this please?
> 4 mezzanine frames means 4_120/60fps = 8 and 4_120/15fps = 32
> Where 120 is recording rate.

Yes. That's what I meant. 
I'm not too bothered by the exact details & trying for "the perfect solution". What matters is that someone who is running the tests & finding failure(s) can better work out when the problem is the camera setup and when the problem is the device under test.

**Comment by jpiesing** [comment]
The various improvements in QR code detection have reduced the relevance of this.
