### ISSUE TITLE
NOT_RUN: No audio segment is detected.

### ISSUE THREAD

**Issue by jpiesing** [cta-wave/device-observation-framework#100]
In the OF 2.0.1 results from the Berlin plugfest, TV 5 and TV 6 had almost all audio observations appear as "NOT_RUN: No audio segment is detected."
When OF 2.0.2 was used on the same recordings, a lot of TV 4 tests where audio was detected with OF 2.0.1 were no longer detected. Looking at the error messages, these may be false matches as discussed in another issue.

Either way, someone needs to take a look at the recordings for TV 5, TV 6 and perhaps TV 4 and see if there is any audio there & if there is, why it's not detected. Is it volume or something else?

**Comment by yanj-github** [comment]
@jpiesing and @louaybassbouss it this Berlin recording or lab recording please? We don't see lots of NOT_RUN's on Berlin recording.

**Comment by rcottingham** [comment]
Hi Jon - with the OF improvements this number has greatly reduced (this is from the file I posted to Causeway after our call yesterday)

![image](https://github.com/user-attachments/assets/93935e8b-7eff-42ad-a51d-d58a973a415c)

OF Update1: addressed https://github.com/cta-wave/device-observation-framework/issues/93
OF Update 2: changes made to add recording device AV offset (calculated automatically as per https://github.com/cta-wave/device-observation-framework/wiki/How-to-calibrate-your-camera-for-in-sync-recording#automated-calibration) and updates as discussed here: https://github.com/cta-wave/device-observation-framework/issues/95 (further refinement in progress).

**Comment by yanj-github** [comment]
@louaybassbouss can you check right code base is used and also config.ini for observation framework is updated as well (dpctf-deploy/observation-config.ini).

**Comment by louaybassbouss** [comment]
> @louaybassbouss can you check right code base is used and also config.ini for observation framework is updated as well (dpctf-deploy/observation-config.ini).

@yanj-github the OF results @jpiesing mentioned in https://github.com/cta-wave/device-observation-framework/issues/100#issuecomment-2535555934 are from a version of last week (OFv2.0.2 with `start_segment_num_tolerance = 3` ). We copied the observation-config.ini from OF repo and changed changed value of `start_segment_num_tolerance` from 0 to 3.

**Comment by yanj-github** [comment]
> > @louaybassbouss can you check right code base is used and also config.ini for observation framework is updated as well (dpctf-deploy/observation-config.ini).
> 
> @yanj-github the OF results @jpiesing mentioned in [#100 (comment)](https://github.com/cta-wave/device-observation-framework/issues/100#issuecomment-2535555934) are from a version of last week (OFv2.0.2 with `start_segment_num_tolerance = 3` ). We copied the observation-config.ini from OF repo and changed changed value of `start_segment_num_tolerance` from 0 to 3.

Thank you, and apologies for not explaining more clearly earlier. The change to start_segment_num_tolerance = 3 will not affect the NOT_RUN results. However, other values in config.ini might. Could you please verify if everything else in your local set up OF configuration matches the updated version? Since we are getting different results, I suspect it might be due to differences in the code execution or configuration.

**Comment by louaybassbouss** [comment]
@yanj-github is `feature` is still the latest version?

**Comment by yanj-github** [comment]
> @yanj-github is `feature` branch is still the latest version?

Yes :)

**Comment by iljagav** [comment]
@yanj-github we can confirm that the issue with `NOT_RUN` observations is solved as you recommended. Maybe you could make `start_segment_num_tolerance = 3` as default in the feature branch? @jpiesing feel free to close this issue
