### ISSUE TITLE
more feedback while running

### ISSUE THREAD

**Issue by jpiesing** [cta-wave/device-observation-framework#11]
Please consider giving a little more feedback while running, e.g. printing a "." for each 10 frames parsed or printing the frame number each 10 frames.

**Comment by yanj-github** [comment]
> 
> 
> Please consider giving a little more feedback while running, e.g. printing a "." for each 10 frames parsed or printing the frame number each 10 frames.

Yes we can do this.

**Comment by jpiesing** [comment]
OK. Done.
