### ISSUE TITLE
seemingly late reporting of results for a test

### ISSUE THREAD

**Issue by jpiesing** [cta-wave/device-observation-framework#12]
It's 20 minutes since the observation framework detected "status=ended" on my current iteration. It's still not attempted to write the results. Is there a reason it waits so long? A manual recording with a camera will likely have irrelevant content on the end and waiting for all that to be analysed is frustrating.

![image](https://user-images.githubusercontent.com/8490792/115886324-182f6e80-a451-11eb-99c4-76a29f6cc6cf.png)

**Comment by jpiesing** [comment]
In fact the report was only logged 30 minutes after status=ended was detected. This feels like a timeout of some kind?

**Comment by yanj-github** [comment]
Thanks Jon, I can see it will help a lot if we would do the observation and discard anything that is not necessarily beforehand rather than wait until the end of the recording. 
We are fine with first till the last-1 tests as OF can see next session start QR codes to move to the observation stage, but not for a one test in a session and the last test. I am not sure if it is a good idea to relay on status=ended to determine the end of each test @louaybassbouss? Instead, can we have an end of session QR code from test runner please? I think this will be more accurate.

**Comment by louaybassbouss** [comment]
> Thanks Jon, I can see it will help a lot if we would do the observation and discard anything that is not necessarily beforehand rather than wait until the end of the recording.
> We are fine with first till the last-1 tests as OF can see next session start QR codes to move to the observation stage, but not for a one test in a session and the last test. I am not sure if it is a good idea to relay on status=ended to determine the end of each test @louaybassbouss?

@yanj-github you can reply on `status=ended` to detect the end of a test. 

> Instead, can we have an end of session QR code from test runner please? I think this will be more accurate.

After the session is completed, you should see the completed page with a QR code. This QR contains the URL of the session overview page like this `http://<HOST_IP>:<PORT>/_wave/overview.html?token=<COMPLETED_SESSIONS_TOKEN>`  and you can use this to detect the end of the session.

**Comment by yanj-github** [comment]
> 
> 
> > Thanks Jon, I can see it will help a lot if we would do the observation and discard anything that is not necessarily beforehand rather than wait until the end of the recording.
> > We are fine with first till the last-1 tests as OF can see next session start QR codes to move to the observation stage, but not for a one test in a session and the last test. I am not sure if it is a good idea to relay on status=ended to determine the end of each test @louaybassbouss?
> 
> @yanj-github you can reply on `status=ended` to detect the end of a test.
> 
> > Instead, can we have an end of session QR code from test runner please? I think this will be more accurate.
> 
> After the session is completed, you should see the completed page with a QR code. This QR contains the URL of the session overview page like this `http://<HOST_IP>:<PORT>/_wave/overview.html?token=<COMPLETED_SESSIONS_TOKEN>` and you can use this to detect the end of the session.
Thanks @louaybassbouss, regarding to the QR code on the overview page, I noticed that it is a different type of QR code compared with anything else. This is not an inverted QR code so OF does not detect this. 

I can I use `status=ended` to detect the end of a test, to make observations and post the result to Test Runner. However, OF still required to carry on processing till the end of the recording (there might be next tests after the current test), as OF will not be able to know where the test session is ended / last test. The user will see OF still running even all the observations are made for the last test which I believe cause confusion to the user.
We can put some timeout, saying when next test QR code not detected within the threshold, then end the OF. However, this is not great. It would be better if OF can be notified as soon as when the session ended.

**Comment by louaybassbouss** [comment]
> Thanks @louaybassbouss, regarding to the QR code on the overview page, I noticed that it is a different type of QR code compared with anything else. This is not an inverted QR code so OF does not detect this.
> 
> I can I use `status=ended` to detect the end of a test, to make observations and post the result to Test Runner. However, OF still required to carry on processing till the end of the recording (there might be next tests after the current test), as OF will not be able to know where the test session is ended / last test. The user will see OF still running even all the observations are made for the last test which I believe cause confusion to the user.
> We can put some timeout, saying when next test QR code not detected within the threshold, then end the OF. However, this is not great. It would be better if OF can be notified as soon as when the session ended.

@yanj-github the completed page is part of the WAVE Test Runner and not the test itself this is why it is not the same. You can use the [Session API](https://github.com/cta-wave/dpctf-test-runner/blob/master/tools/wave/docs/rest-api/tests-api/read-session.md)  to get the lists of tests within a session and you can check which tests are observed on your side and so you can detect the end. I hope this helps.

**Comment by jpiesing** [comment]
I can't reproduce this. Closing it & will re-open it if necessary.
