### ISSUE TITLE
test codes required to be changed

### ISSUE THREAD

**Issue by yanj-github** [cta-wave/device-observation-framework#13]
Test codes are changed on Tests:
https://github.com/cta-wave/dpctf-tests/issues/33

OF requires to apply same changes.

**Comment by louaybassbouss** [comment]
@yanj-github if you face any issue after renaming the filenames please let us know

**Comment by jpiesing** [comment]
As the origial reporter, @yanj-github can this issue be closed?

**Comment by yanj-github** [comment]
Yes this is done and released now.
