### ISSUE TITLE
deployment should work 'out of the box' without editing any configuration files or similar

### ISSUE THREAD

**Issue by jpiesing** [cta-wave/device-observation-framework#14]
Ideally the deployment would "just work" 'out of the box' without anyone needing to do anything such as editing configuration files.

The only one I can remember is editing config.ini to set the test_runner_url, e.g.

test_runner_url = http://localhost:8000

Please consider making the installation script set this.
If there would be a test runner on localhost:8000 (the default?) then ask the user if they want that. Otherwise ask them.
Check that it works.

**Comment by yanj-github** [comment]
Thanks @jpiesing Instead, can we make test_runner_url = http://localhost:8000 a default value as normally test runner and OF are intended to be installed on the same machine?

**Comment by jpiesing** [comment]
> Thanks @jpiesing Instead, can we make test_runner_url = http://localhost:8000 a default value as normally test runner and OF are intended to be installed on the same machine?

Could you also make the installation process test that a test runner is running on http://localhost:8000?

**Comment by yanj-github** [comment]
> 
> 
> > Thanks @jpiesing Instead, can we make test_runner_url = http://localhost:8000 a default value as normally test runner and OF are intended to be installed on the same machine?
> 
> Could you also make the installation process test that a test runner is running on http://localhost:8000?

The installation script doent have ability to check the test runner but OF can check it.
We can print out the error message when user run the OF if test runner is not found and inform user to check it.

**Comment by jpiesing** [comment]
> The installation script doent have ability to check the test runner but OF can check it.

Why can't the installation script attempt to connect to localhost:8000 and see if there's something listening? If it cannot connect then a warning could be given that the user may need to edit the config file.

**Comment by yanj-github** [comment]
> 
> 
> > The installation script doent have ability to check the test runner but OF can check it.
> 
> Why can't the installation script attempt to connect to localhost:8000 and see if there's something listening? If it cannot connect then a warning could be given that the user may need to edit the config file.

Just wanted to confirm if I am with you. Do you mean adding this check part of setup_dev_environment.sh please? Yes, I think we can do this.

**Comment by jpiesing** [comment]
> Just wanted to confirm if I am with you. Do you mean adding this check part of setup_dev_environment.sh please? Yes, I think we can do this.

Yes.
Check if something is listening on localhost:8000. If not generate a warning that config.ini may need to be edited.

**Comment by jpiesing** [comment]
Confirmed.
