### ISSUE TITLE
out of order frames detected on “Random Access to Fragment” Test

### ISSUE THREAD

**Issue by yanj-github** [cta-wave/device-observation-framework#18]
On “Random Access to Fragment” Test, the frame 603 is detected before 602. 
Further investigation found that the 1st display is “fading-up” progressively from the top of the screen to the bottom. It contains frame number 602 and 603, but 602 is lower down on the screen so is not yet bright enough to be recognised.

The figure below shows a QR code with frame 603 on the top and 602 just below it, which is yet to show clearly:
 
![image](https://user-images.githubusercontent.com/59022223/119528273-f63f4980-bd78-11eb-96e8-aab96c60ad28.png)

This figure shows the next frame of the capture, where QR codes with 603 and 602 are both detected.
![image](https://user-images.githubusercontent.com/59022223/119528328-00f9de80-bd79-11eb-8d6a-ef423e32a60a.png)

**Comment by jpiesing** [comment]
Can someone just pick a different fragment where this problem doesn't happen?

**Comment by yanj-github** [comment]
Thanks @jpiesing that is a good sugguestion.
However, that wont avoid the this problme in total, if some frames missing at the beginning.

**Comment by yanj-github** [comment]
Hi @louaybassbouss, is it possible for all the random access tests that the test runner changes to access from the fragment / time (defines in test-config.json) that accessing frame has QR on top row?

**Comment by yanj-github** [comment]
As far as I am aware test runner can set different random access values for each test on test-config.json file. 
User can pick different random access values so that test starting from any top QR code.
Can you confirm this @louaybassbouss?
@jpiesing If you happy with this approach, feel free to close this issue, Thanks.

**Comment by louaybassbouss** [comment]
> As far as I am aware test runner can set different random access values for each test on test-config.json file.
> User can pick different random access values so that test starting from any top QR code.
> Can you confirm this @louaybassbouss?
> @jpiesing If you happy with this approach, feel free to close this issue, Thanks.

@yanj-github  yes I can confirm

**Comment by yanj-github** [comment]
@jpiesing can I close this issue? Or you want to do further checks please?

**Comment by jpiesing** [comment]
Is this issue fixed or not?
Either;
- The black background fixes the problem or
- Someone has changed the random access target frame or
- Something else

The fact that it's possible for someone to change the random access target frame to be one where this problem doesn't happen is **not** enough to close the issue unless/until someone has actually made that change & checked that it fixes the problem.

**Comment by yanj-github** [comment]
@jpiesing If we won't change OF can we close this issue please?

**Comment by yanj-github** [comment]
This is a known issue for certain device (which starts content fading from top down) and only using QR code the observation we can do is pretty limited at this stage. From the call at 31/08/2021 it is agreed that nothing need to be done for now either on mezzanine or OF end. Closing this issue now.
