### ISSUE TITLE
The presented sample matches the one reported by the currentTime value within the tolerance of the sample duration.

### ISSUE THREAD

**Issue by yanj-github** [cta-wave/device-observation-framework#19]
This observation failed to all the tests with allowed tolerance is 10ms. Please see measured time differeces below.

e.g: 
Time difference between Test Runner reported media currentTime and actual media time exceeded tolerance for following events: currentTime=0.083509 time_diff=99.491;  currentTime=0.288148 time_diff=61.852;  currentTime=0.52112 time_diff=28.88;  currentTime=0.673307 time_diff=76.693;  currentTime=0.877083 time_diff=55.917;  currentTime=1.014043 time_diff=68.957;  currentTime=1.184632 time_diff=98.368;  currentTime=1.414505 time_diff=102.495;  currentTime=1.670653 time_diff=96.347;  currentTime=1.909997 time_diff=57.003;  currentTime=2.064947 time_diff=35.053;  currentTime=2.280391 time_diff=119.609;  currentTime=2.81638 time_diff=83.62;  currentTime=3.110082 time_diff=106.918;  currentTime=3.336761 time_diff=96.239;  currentTime=3.559719 time_diff=90.281;  currentTime=3.772708 time_diff=44.292;  currentTime=3.92576 time_diff=41.24;  currentTime=4.079557 time_diff=53.443;  currentTime=4.242514 time_diff=90.486;  currentTime=4.497108 time_diff=102.892;  currentTime=4.730837 time_diff=69.163;  currentTime=4.954605 time_diff=112.395;  currentTime=5.199264 time_diff=67.736;  currentTime=5.376242 time_diff=90.758;  currentTime=5.590165 time_diff=92.835;  currentTime=5.843364 time_diff=56.636;  currentTime=6.06697 time_diff=83.03;  currentTime=6.290698 time_diff=76.302;  currentTime=6.503479 time_diff=79.521;  currentTime=6.696196 time_diff=70.804;  currentTime=6.889581 time_diff=60.419;  currentTime=7.062508 time_diff=54.492;  currentTime=7.194755 time_diff=72.245;  currentTime=7.356979 time_diff=110.021;  currentTime=7.610839 time_diff=106.161;  currentTime=7.85523 time_diff=94.77;  currentTime=8.088637 time_diff=94.363;  currentTime=8.271258 time_diff=95.742;  currentTime=8.495082 time_diff=54.918;  currentTime=8.678835 time_diff=71.165;  currentTime=8.842898 time_diff=74.102;  currentTime=9.015839 time_diff=117.161;  currentTime=9.279535 time_diff=120.465;  currentTime=9.504224 time_diff=95.776;  currentTime=9.749472 time_diff=100.528;  currentTime=10.005476 time_diff=94.524;  currentTime=10.219806 time_diff=80.194;  currentTime=10.40472 time_diff=112.28;  currentTime=10.649257 time_diff=67.743; ...too many failures, reporting truncated. Total failure count is 300.

**Comment by andyburras** [comment]
FYI: This observation is testing: "_The presented sample matches the one reported by the currentTime value within the tolerance of the sample duration_". The Test Runner generates a status QR code containing the reported currentTime of the media playback. Generating this code takes a measurable amount of time, so Test Runner also places this delay time as the 'delay' parameter in the **next** status QR code.
Observation Framework extracts these QR codes, and the mezzanine QR codes and uses the following logic:

```
        sample_tolerance_in_recording = 1000/mezzanine_frame_rate/(1000/camera_frame_rate) = camera_frame_rate/mezzanine_frame_rate
        sample_tolerance = 1000/mezzanine_frame_rate
        
        target_camera_frame_num_of_ct_event = ct_event.first_seen_camera_frame_num - (ct_event.d / Dr)
        first_possible_camera_frame_num_of_target = target_camera_frame_num_of_ct_event - CAMERA_FRAME_ADJUSTMENT - sample_tolerance_in_recording
        last_possible_camera_frame_num_of_target = target_camera_frame_num_of_ct_event + CAMERA_FRAME_ADJUSTMENT  + sample_tolerance_in_recording
        
        for first_possible_camera_frame_num_of_target to last_possible_camera_frame_num_of_target
                foreach mezzanine_qr_code on camera_frame that within the range
                        if mezzanine_qr_code.media_time == (ct_event.current_time +/- (sample_tolerance + tolerance))
                                test is PASSED
```

**Comment by jpiesing** [comment]
I was going to suggest 1 frame but at 30Hz, that is 33ms and most of the above are beyond that.
Even 2 frames at 30Hz would be 66.7ms and most of the above are beyond that.

What platform are the above results measured on? PC? TV? Mobile? If it's PC then I think there may be a problem with the measurement approach. If it's TV then it's worse than I feared :(

**Comment by yanj-github** [comment]
@jpiesing  the results were measured on a TV.

**Comment by jpiesing** [comment]
> @jpiesing the results were measured on a TV.

Would it be easy for you to repeat the measurement on a PC?

**Comment by yanj-github** [comment]
@jpiesing yes, I can test this on a PC, because I need to do some network set up, I cannot do this today, but I will try it out by the end of this week.

**Comment by jpiesing** [comment]
Values that make sense could be somewhere between 2 and 5 frames.
At 30fps, 2 is 67, 3 is 100, 4 is 133 and 5 is 167.
Looking at the numbers in the problem report, 67 would still result in a lot of failures. 100 would result in some failures. 133 would result in few to no failures.

Let's see what it looks like on a PC and a phone and go on from there.

**Comment by jpiesing** [comment]
The proposal in https://github.com/cta-wave/device-observation-framework/issues/22 would make it easier to analyse what performance is found in the real world.

**Comment by yanj-github** [comment]
Hi @jpiesing I have managed to try this out on a windows pc, the result seems much better on a laptop.
This observation failed on two events, and one of them are at current_time 0 i think is is due to unsbale to detect frame 0 (the green screen). And one at currentTime=0.033333. Please see the following result.

Allowed tolerance is 10. Time difference between Test Runner reported media currentTime and actual media time exceeded tolerance for following events: currentTime=0 time_diff=1.7976931348623157e+308;  currentTime=0.033333 time_diff=83.667;

**Comment by jpiesing** [comment]
I look forward to trying it on a phone.

**Comment by yanj-github** [comment]
@jpiesing There are lots of frames missing when I test on a phone. So wobe be able to test this current time match observation. Do you have same problem on your phone if you had chance to test on a phone please? The recording shows the frames actually is missing so this is not a camera set up issue or OF.

**Comment by jpiesing** [comment]
@yanj-github The recording I sent you by wetransfer was made on a phone. I can't run the observation framework on that recording due to the ID issue . I've stepped through it frame by frame. I think the frame playback rate is uneven & some frames may only be present for much shorter than they should be when it's catching up but they all seemed to be there.
Perhaps you have some debugging tools to see what is reported.

**Comment by yanj-github** [comment]
@jpiesing  I have manged to run OF on your recordings in debug mode. There are some mid frames missing. But it is "PASS" for the current time observation. 
Please see the following results:
    {
        "status": "FAIL",
        "message": " First frame found is 1, expected to start from 1. First frame number tolerance is 1. Last frame found is 1799, expected to end at 1800. Last frame number tolerance is 0. Mid frame number tolerance is 0. Frame 663 is missing. Frame 685 is missing. Frame 1429 is missing. Frame 1444 is missing. Frame 1631 is missing.",
        "name": "[OF] Every sample S[k,s] shall be rendered and the samples shall be rendered in increasing presentation time order."
    },
    {
        "status": "FAIL",
        "message": "Playback duration 59968.21ms does not match expected duration 60000.0ms +/- tolerance of 10ms. Allowed tolerance is 10ms. Starting missing frame tolerance is 0. Ending missing frame tolerance is 0.",
        "name": "[OF] The playback duration of the playback matches the duration of the CMAF Track, i.e. TR [k, S] = TR [k, 1] + td[k]."
    },
    {
        "status": "PASS",
        "message": "Maximum permitted startup delay is 120ms.The presentation start up delay is 85.3167ms",
        "name": "[OF] The start-up delay should be sufficiently low, i.e., TR [k, 1] - Ti < TSMax."
    },
    {
        "status": "PASS",
        "message": " Allowed tolerance is 10.",
        "name": "[OF] The presented sample matches the one reported by the currentTime value within the tolerance of the sample duration."
    }

**Comment by jpiesing** [comment]
> @jpiesing I have manged to run OF on your recordings in debug mode. There are some mid frames missing. But it is "PASS" for the current time observation.

So that is a lot better than the mobile phone that you used?

**Comment by yanj-github** [comment]
Please also note that you have used 30 fps content while my recording is 60 fps. But still I think the device that you used is indeed a lot better than mine. 

It means lots of failure on this observation is on specific device as it only shows many failures on the TV that I have tested. So the measurement approcach looks fine to me. 

What do yo think @jpiesing?
Are you happy to keep the tolerance 10ms for now?

**Comment by jpiesing** [comment]
> Please also note that you have used 30 fps content while my recording is 60 fps.

I'll do another recording with 60fps content.

**Comment by jpiesing** [comment]
> > Please also note that you have used 30 fps content while my recording is 60 fps.
> 
> I'll do another recording with 60fps content.

60Hz recording uploading to wetransfer at the moment.

**Comment by yanj-github** [comment]
Hi @jpiesing run OF with 60 fps content recording that you have sent to me:
Total of missing frames is 80. So the OF is stopped observing further as the missing_frame_threshold  is 50.

To do further debug, I have changed missing_frame_threshold to 100 and got the following result:
[high_debug.txt](https://github.com/cta-wave/device-observation-framework/files/6599452/high_debug.txt)

**Comment by yanj-github** [comment]
@jpiesing 
If we don't require any further changes on OF I will close this issue. 

The presented sample matches the one reported by the currentTime value within the **tolerance** of the sample duration.
What is the tolerance? "tolerance" is required to be defined from the Spec.
Value of "tolerance"s are defined in the TR configuration file.
