### ISSUE TITLE
please add a verbose mode to the observation framework to aid debugging

### ISSUE THREAD

**Issue by jpiesing** [cta-wave/device-observation-framework#21]
Please add a verbose mode to the observation framework which provides feedback as the watermarks are being analyzed. Something that someone can copy/paste into a redmine or github issue.

**Comment by yanj-github** [comment]
Thanks @jpiesing We can change OF to display debugging logs on console when log level is set to debuging.

**Comment by jpiesing** [comment]
> Thanks @jpiesing We can change OF to display debugging logs on console when log level is set to debuging.

@yanj-github How is the log level set?

**Comment by yanj-github** [comment]
By passing "--log debug" when running OF. e.g "python observation_framework.py --input <record_file_path> --log debug"

**Comment by jpiesing** [comment]
> By passing "--log debug" when running OF. e.g "python observation_framework.py --input <record_file_path> --log debug"

Is that documented anywhere? I can't see it in README.md and certainly it's new to me.

**Comment by yanj-github** [comment]
No it is not there yet I will have to make changes to OF to enable this. Sorry for the confusion.

**Comment by yanj-github** [comment]
"--log debug" when running OF shows full debug message now. @jpiesing are you happy to close this issue please?

**Comment by jpiesing** [comment]
Done.
