### ISSUE TITLE
export data on variation between currentTime and media time in spreadsheet friendly format

### ISSUE THREAD

**Issue by jpiesing** [cta-wave/device-observation-framework#22]
It seems some thought will be needed about tolerances for the fit between currentTime and media time.
This would be a lot easier if it was possible to export the variation between the two in a spreadsheet friendly format (e.g. .csv).
I'm not sure if this would be needed in the long term but it could be quite helpful in the short and perhaps medium term.

**Comment by yanj-github** [comment]
Hi @jpiesing  We can export data to a CSV file for each test in “logs/<session_id>/<test_time_match>”, can you confirm if the following is what you are expecting please?

CSV file will look like: 
currentTime        time_diff
… …
0.083509             99.491
0.288148             61.852
0.52112               28.88
 0.673307            76.693
 0.877083            55.917
1.014043             68.957
… …

**Comment by jpiesing** [comment]
@yanj-github Looks good to me.

**Comment by yanj-github** [comment]
@jpiesing Do we want CSV file to include  time_diffs that are within the tolerence as well please? Or you prefer CSV file contains only those failing ones?

**Comment by jpiesing** [comment]
> @jpiesing Do we want CSV file to include time_diffs that are within the tolerence as well please? Or you prefer CSV file contains only those failing ones?

All of them please as the reason for the CSV file is to enable an informed discussion about what the tolerance should be.

**Comment by yanj-github** [comment]
[avc_15_30_60-local-sequential-track-playback__avc_sets_15_30_60_t20_time_diff.txt](https://github.com/cta-wave/device-observation-framework/files/6687894/avc_15_30_60-local-sequential-track-playback__avc_sets_15_30_60_t20_time_diff.txt)
@jpiesing I have exported a csv file based on the last recording (C0026) that you have sent me.
Github diesnt support the csv file so I hav eupdated as txt format, you can just rename it to .csv when you look at it. 
Let us know if this is what you are expecting please?

**Comment by yanj-github** [comment]
@jpiesing I have noticed current time reported 0 at some point within the duration from your recording. 
I havent seen this before. It doesnt occure in recordings taken on a TV that I have tested on.

Current Time | Time Difference
-- | --
0 | 1.7976931348623157e+308
19.584 | 30.416
250.198 | 16.802
0 | 367
500.275 | 16.725
750.379 | 32.621
1000.484 | 16.516
1250.733 | 32.267
1500.811 | 16.189
1750.341 | 16.659
2010.726 | 22.274
2250.397 | 16.603
2504.204 | 12.796
0 | 2583
2750.298 | 0.298
3000.321 | 16.679
3250.532 | 16.468
3500.331 | 16.669
3750.624 | 0.624
4000.439 | 16.561
4250.479 | 16.521
0 | 4400
4500.278 | 32.722



</body>

</html>

**Comment by jpiesing** [comment]
@yanj-github Please raise a new issue in https://github.com/cta-wave/dpctf-tests for currentTime being zero.

**Comment by jpiesing** [comment]
.csv file reviewed. OK.
