### ISSUE TITLE
reference 'known good' recording that is successfully analysed

### ISSUE THREAD

**Issue by jpiesing** [cta-wave/device-observation-framework#25]
I think it might be good to have a reference or 'known good' recording that is successfully analysed by the OF that people can look at & run the OF on. I realise this can't be 100% as the OF will fail when attempting to post the results of a non-existing test run but still, I think this will make people more confident about their own test runs when they're trying to get everything going.

**Comment by pshorrock** [comment]
@jpiesing after discussing this we are unsure what this will provide over and above the guidance in the supporting documentation (i.e. images), especially if not just being viewed to see what a good capture looks like. Just exercising the OF code (as it will not be able to post the results and check the API / the test runner is able to be communicated with) isn't we think likely to yield many clues as to what may be wrong in a setup where it is more likely to be an issue with additional light artifacts on a screen, poor camera positioning or being focused in sufficiently on a small device such as a phone. We are not against providing something so long as we are clear on how to present it and what materially the user can get from it. Happy to discuss if/as required.

**Comment by jpiesing** [comment]
I'm grasping at ideas for how to make it easier for test engineers to be more comfortable that they have a working test setup. Any suggestions are welcome.
