### ISSUE TITLE
option to run OF with adaptive threshold

### ISSUE THREAD

**Issue by jpiesing** [cta-wave/device-observation-framework#26]
Please add an option for users of the OF to run it with an adaptive threshold even though this increases the execution time. This will help users determine if failures are due to their camera setup or due to the device under test. It's OK to have the default be without adaptive threshold but it should be possible to run with it.

**Comment by jpiesing** [comment]
I can see the references to this in the code but there's nothing in the documentation. Please could you update the documentation to tell users that the option exists & how to use it.

**Comment by yanj-github** [comment]
> 
> 
> @yanj-github I can see the references to this in the code but there's nothing in the documentation. Please could you update the documentation to tell users that the option exists & how to use it.

It is already documented on readme:
--scan intensive makes the QR code recognition more robust by allowing an additional adpativethresholded scan, however this will increase prossing time. This option is to be used where it is difficult to take clear repcordings, such as testing on a small screen devices like mobile phones.

**Comment by jpiesing** [comment]
> It is already documented on readme:
> --scan intensive makes the QR code recognition more robust by allowing an additional adaptive thresholded scan, however this will increase prossing time. This option is to be used where it is difficult to take clear repcordings, such as testing on a small screen devices like mobile phones.

Ah. I was looking for references to "adaptive" & missed that text because it didn't use the magic word.

**Comment by yanj-github** [comment]
@jpiesing if you happy with the change and the documentation, can we close this issue please?

**Comment by jpiesing** [comment]
Closing.
