### ISSUE TITLE
presentation startup delay is negative

### ISSUE THREAD

**Issue by jpiesing** [cta-wave/device-observation-framework#27]
I'm seeing a pass on the presentation startup delay because the delay is negative. Please see below.

![image](https://user-images.githubusercontent.com/8490792/123633469-8b6eab80-d819-11eb-9466-960bbf161e12.png)

**Comment by yanj-github** [comment]
Thanks @jpiesing for reporting. We just spotted similar problem here on one of our recordings. Where the problem was the 1st frame presented before the test status changed to last action is play. Where we thought content start playing always after the play command. 
Can you send me your recording which shows the issue so I can do further diagnostic please?

**Comment by jpiesing** [comment]
@yanj-github You will get an email from wetransfer.com any moment.

**Comment by yanj-github** [comment]
1st frame (frame 1) was detected at camera_frame=1168 and 1st status action=play was detected at camera_frame=1242 with delay which is reported on next status change "delay=24". 
OF calculated a gap between 1st status "action=play" and 1st mezzanine detection frame-based recording frame rate. 
It appears that 1st frame is detected before the 1st status "action=play".
Therefore, start up delay is negative. 
[qr_code_list.zip](https://github.com/cta-wave/device-observation-framework/files/6727386/qr_code_list.zip)

Based on observation logic, start up delay should be lower than the 250ms which is does pass the test. 
However it is strange that 1st frame is shown before the status change "action=play".

@louaybassbouss, can you help diagnostic it to check whether tesr runner send "action=play" at correct time please? The full qr code extraction is attached. 
Does test running sending "action=play" when it send the command or it send it when it received response of the play() acknowledgement?

**Comment by louaybassbouss** [comment]
> 1st frame (frame 1) was detected at camera_frame=1168 and 1st status action=play was detected at camera_frame=1242 with delay which is reported on next status change "delay=24".
> OF calculated a gap between 1st status "action=play" and 1st mezzanine detection frame-based recording frame rate.
> It appears that 1st frame is detected before the 1st status "action=play".
> Therefore, start up delay is negative.
> [qr_code_list.zip](https://github.com/cta-wave/device-observation-framework/files/6727386/qr_code_list.zip)
> 
> Based on observation logic, start up delay should be lower than the 250ms which is does pass the test.
> However it is strange that 1st frame is shown before the status change "action=play".
> 
> @louaybassbouss, can you help diagnostic it to check whether tesr runner send "action=play" at correct time please? The full qr code extraction is attached.
> Does test running sending "action=play" when it send the command or it send it when it received response of the play() acknowledgement?

@yanj-github  HTML5 players usually show the first frame even if you don't call a play().

**Comment by yanj-github** [comment]
Thanks @louaybassbouss and @jpiesing, I will make change so that OF will measure from 2nd detected frame instead of 1st one.

**Comment by jpiesing** [comment]
@yanj-github Would the test showing the first frame before play really starts also cause the duration failure shown in the screen capture in the original problem description?

**Comment by yanj-github** [comment]
Yes @jpiesing we are changing the duration calculation as well to measure from 2nd detected frame. And add duration of 1st frame.

**Comment by yanj-github** [comment]
Hi @jpiesing  we have managed to test with your latest recording c0036 which shows pass for the duration check.
"Playback duration is 59993.2ms, CMAF track duration is 60000.0ms. Allowed tolerance is 10ms. Starting missing frame tolerance is 0. Ending missing frame tolerance is 0."

However, the start up delay is still negative. "Maximum permitted startup delay is 120ms.The presentation start up delay is -14.3583ms"

From the detection I can see device shows frame 2 as soon as play is called. This made start up delay is negative, I was thinking after play is called device should display frame 1 for first frame duration which is 1000/30=33.33ms in this case. frame rate is 30fps. Should observation fail or pass in this case?

**Comment by jpiesing** [comment]
> From the detection I can see device shows frame 2 as soon as play is called. This made start up delay is negative, I was thinking after play is called device should display frame 1 for first frame duration which is 1000/30=33.33ms in this case. frame rate is 30fps. Should observation fail or pass in this case?

This needs wider discussion about what is the definition of start-up delay. I will raise a new github issue.

**Comment by yanj-github** [comment]
Here are some of our results if this is helpful:

- Testing on a phone PASS
Maximum permitted startup delay is 120ms.The presentation start up delay is 33.5417ms

- Testing on a laptop PASS
Maximum permitted startup delay is 120ms.The presentation start up delay is 78.7667ms

- Testing on a TV FAIL
Maximum permitted startup delay is 120ms.The presentation start up delay is 139.025ms

**Comment by jpiesing** [comment]
@yanj-github I think we can close this issue. Do you agree? If so then please do so.

**Comment by jpiesing** [comment]
> From the detection I can see device shows frame 2 as soon as play is called. This made start up delay is negative, I was thinking after play is called device should display frame 1 for first frame duration which is 1000/30=33.33ms in this case. frame rate is 30fps. Should observation fail or pass in this case?

@yanj-github Please can you share the timeline of (say) the first 10 frames?
I think what matters is when linear playback starts - i.e. frames start being displayed at the correct frame rate.
If frame 1 is shown without waiting for play to be called & frame 2 is shown immediately play is called then what about frame 3?

**Comment by yanj-github** [comment]
2820 |   |   |   |   | buffering | initialize | 0 | 133
-- | -- | -- | -- | -- | -- | -- | -- | --
2821 | L1 | 33 | 1 | 30 |   |   |   |  
2821 |   |   |   |   | buffering | initialize | 0 | 133
2822 | L1 | 33 | 1 | 30 |   |   |   |  
2822 |   |   |   |   | buffering | initialize | 0 | 133
2823 | L1 | 33 | 1 | 30 |   |   |   |  
2823 |   |   |   |   | buffering | initialize | 0 | 133
2824 | L1 | 33 | 1 | 30 |   |   |   |  
2824 |   |   |   |   | buffering | initialize | 0 | 133
2824 | L1 | 67 | 2 | 30 |   |   |   |  
2825 | L1 | 67 | 2 | 30 |   |   |   |  
2825 | L1 | 33 | 1 | 30 |   |   |   |  
2826 | L1 | 33 | 1 | 30 |   |   |   |  
2826 | L1 | 67 | 2 | 30 |   |   |   |  
2827 | L1 | 100 | 3 | 30 |   |   |   |  
2827 | L1 | 67 | 2 | 30 |   |   |   |  
2827 |   |   |   |   | playing | play | 0 | 104
2828 | L1 | 133 | 4 | 30 |   |   |   |  
2828 | L1 | 100 | 3 | 30 |   |   |   |  
2828 |   |   |   |   | playing | play | 0 | 104
2829 | L1 | 100 | 3 | 30 |   |   |   |  
2829 | L1 | 133 | 4 | 30 |   |   |   |  
2829 |   |   |   |   | playing | play | 0 | 104
2830 |   |   |   |   | playing | play | 0 | 104
2830 | L1 | 133 | 4 | 30 |   |   |   |  
2831 |   |   |   |   | playing | play | 0 | 104
2831 | L1 | 133 | 4 | 30 |   |   |   |  
2832 |   |   |   |   | playing | play | 0 | 104
2832 | L1 | 133 | 4 | 30 |   |   |   |  
2833 | L1 | 133 | 4 | 30 |   |   |   |  
2833 |   |   |   |   | playing | play | 0 | 104
2833 | L1 | 167 | 5 | 30 |   |   |   |  
2834 | L1 | 167 | 5 | 30 |   |   |   |  
2834 | L1 | 133 | 4 | 30 |   |   |   |  
2834 |   |   |   |   | playing | play | 0 | 104
2835 | L1 | 133 | 4 | 30 |   |   |   |  
2835 | L1 | 167 | 5 | 30 |   |   |   |  
2835 |   |   |   |   | playing | play | 0 | 104
2836 |   |   |   |   | playing | play | 0 | 104
2836 | L1 | 167 | 5 | 30 |   |   |   |  
2837 |   |   |   |   | playing | play | 0 | 104
2837 | L1 | 167 | 5 | 30 |   |   |   |  
2838 |   |   |   |   | playing | play | 0 | 104
2838 | L1 | 167 | 5 | 30 |   |   |   |  
2839 | L1 | 167 | 5 | 30 |   |   |   |  
2839 |   |   |   |   | playing | play | 0 | 104
2840 |   |   |   |   | playing | play | 0 | 104
2840 | L1 | 167 | 5 | 30 |   |   |   |  
2841 | L1 | 167 | 5 | 30 |   |   |   |  
2842 | L1 | 167 | 5 | 30 |   |   |   |  
2842 | L1 | 200 | 6 | 30 |   |   |   |  
2843 | L1 | 167 | 5 | 30 |   |   |   |  
2843 | L1 | 200 | 6 | 30 |   |   |   |  
2843 | L1 | 267 | 8 | 30 |   |   |   |  
2843 |   |   |   |   | playing | play | 0.087453 | 44
2844 |   |   |   |   | playing | play | 0.087453 | 44
2844 | L1 | 200 | 6 | 30 |   |   |   |  
2844 | L1 | 267 | 8 | 30 |   |   |   |  
2845 |   |   |   |   | playing | play | 0.087453 | 44
2845 | L1 | 267 | 8 | 30 |   |   |   |  
2846 |   |   |   |   | playing | play | 0.087453 | 44
2846 | L1 | 267 | 8 | 30 |   |   |   |  
2847 | L1 | 300 | 9 | 30 |   |   |   |  
2847 | L1 | 267 | 8 | 30 |   |   |   |  
2847 |   |   |   |   | playing | play | 0.087453 | 44
2848 | L1 | 300 | 9 | 30 |   |   |   |  
2848 | L1 | 267 | 8 | 30 |   |   |   |  
2848 |   |   |   |   | playing | play | 0.087453 | 44
2849 | L1 | 300 | 9 | 30 |   |   |   |  
2849 |   |   |   |   | playing | play | 0.087453 | 44
2849 | L1 | 267 | 8 | 30 |   |   |   |  
2850 | L1 | 300 | 9 | 30 |   |   |   |  
2850 |   |   |   |   | playing | play | 0.087453 | 44
2851 | L1 | 300 | 9 | 30 |   |   |   |  
2851 | L1 | 333 | 10 | 30 |   |   |   |

**Comment by yanj-github** [comment]
Thanks @jpiesing I am happy to close this for now can you confirm it is fine to you as well.
ATM OF calculates start up delay by time gap between play event and 2nd frame and correct frame 1 duration based on the given frame rate.

**Comment by yanj-github** [comment]
@jpiesing OF changed to calculates start up delay by time gap between play event and 2nd frame and correct frame 1 duration based on the given frame rate. 
Can you post qr_code_list.csv file here so that I can check if OF does calculation correctly please?

**Comment by jpiesing** [comment]
[session.log](https://github.com/cta-wave/device-observation-framework/files/6994035/session.log)
[qr_code_list.csv](https://github.com/cta-wave/device-observation-framework/files/6994036/qr_code_list.csv)
[avc_12.5_25_50-2021-07-07-local-sequential-track-playback__t20_time_diff.csv](https://github.com/cta-wave/device-observation-framework/files/6994037/avc_12.5_25_50-2021-07-07-local-sequential-track-playback__t20_time_diff.csv)
[avc_12.5_25_50-2021-07-07-local-sequential-track-playback__t1_time_diff.csv](https://github.com/cta-wave/device-observation-framework/files/6994038/avc_12.5_25_50-2021-07-07-local-sequential-track-playback__t1_time_diff.csv)

I've sent you the recording via wetransfer.com.

**Comment by jpiesing** [comment]
I did a second recording which doesn't show this problem.

![image](https://user-images.githubusercontent.com/8490792/129601695-c08794c8-a5dd-4900-9384-d3dfc26caa41.png)
![image](https://user-images.githubusercontent.com/8490792/129601747-98930862-71eb-4790-a6d3-a5361a4f4789.png)

**Comment by jpiesing** [comment]
I'm re-running the OF on the first recording with adaptive mode enabled. I'll upload the results when it's done.

**Comment by yanj-github** [comment]
Disgnose t1 negative result:

1900 | L1 | 80 | 2 | 25 |   |   |   |  
-- | -- | -- | -- | -- | -- | -- | -- | --
1906 |   |   |   |   | playing | play | 0 | 58
1926 |   |   |   |   | playing | play | 0.095149 | 48

1st play is at 1906 camera frame rate with delay 48.
1906 - 48/(1000/120) = 1900.24
Frame 2 is at 1900 camera frame rate. The content is 25fps, correct frame 1 duration based on the given frame rate. 1000/25=40ms 
1900 - 40/(1000/120)=1895.20

diff = (1895.20 - 1900.24) * (1000/120) = -42ms

OF is doing correct calculation. It seems like that device is starting to play from 2nd frame instead of 1st. It seems that stight after the play event the 2nd frame is displayed.

**Comment by yanj-github** [comment]
Further discussions required. This is not OF bug but if you would like OF to do differently let us know.

**Comment by jpiesing** [comment]
> Further discussions required. This is not OF bug but if you would like OF to do differently let us know.

I think there is an OF bug here. This is being reported as a pass when it should not be.

**Comment by yanj-github** [comment]
> 
> 
> > Further discussions required. This is not OF bug but if you would like OF to do differently let us know.
> 
> I think there is an OF bug here. This is being reported as a pass when it should not be.

Thanks Jon, should OF report failure when the start up delay is negative? Or do you want us to change the way OF calculte the start up delay?

**Comment by jpiesing** [comment]
I think the group needs to discuss the following question ...

What should the OF do when a device doesn't show the first frame (which is a different observation)?
- Fail this observation too because this observation depends on that observation?
- Measure the time to the first frame that is shown even if it's not the first frame that should be shown & potentially report a pass if the delay to the first frame shown is less than the threshold?

Either way, IMHO what's currently there is wrong.

I lean towards the second of these - measure the delay to when the first frame is shown even if that isn't the first frame that should be shown.

**Comment by yanj-github** [comment]
Thanks @jpiesing for the clarification. We prefer the seconds as well, so that an observation is not depends on the other observation. 
The challenge here is where to measure the start-up delay to from the play event. It seems to me that different devices seems behave differently to load() and play(). e.g: some devices display frame 1 on load() and start playing from frame 2, others display black screen on load() and starts playing from frame 1 and there are also the cases that some frames missing at the beginning as well. To consider all these different cases we propose the following solution:

We can measure the start-up delay between play event and the next detected frame / frame change after the play event no matter which frame number it is. Any frames detected before the play event are ignored. This will prevent any negative start-up delay. 

Any comments and suggestions will be helpful. Thanks.

**Comment by jpiesing** [comment]
@yanj-github The same dependency applies to the observation for the duration. If the first frame is not displayed then the duration measurement observation will report a fail. Is this correct?

**Comment by yanj-github** [comment]
> 
> 
> @yanj-github The same dependency applies to the observation for the duration. If the first frame is not displayed then the duration measurement observation will report a fail. Is this correct?

No, but it depands. The missing frames not directly cause the duration check to fail. Each observations calculated and measured seperatly at OF. One observation does not directly depand on another observation or they are inter-related. However, some missing frames may lead to duration check to fail.
Curretnly, OF measures duration from 2nd detected frame to the last detected frame (no matter what frame number it is) and add one frame duration. 
Can we discuss this further on the next call please?

**Comment by yanj-github** [comment]
Hi @jpiesing we are still waiting for comments on:

- Regarding to start-up delay measurement:

We can can the OF to measure the start-up delay between play event and the next detected frame / frame change after the play event no matter which frame number it is. Any frames detected before the play event are ignored. This will prevent any negative start-up delay.

- Regarding to duration measurement:

Currently, OF measures duration from 2nd detected frame to the last detected frame (no matter what frame number it is) and add one frame duration. 
Are we happy with what it is now please?

**Comment by jpiesing** [comment]
>     * Regarding to duration measurement:
> 
> 
> Currently, OF measures duration from 2nd detected frame to the last detected frame (no matter what frame number it is) and add one frame duration.
> Are we happy with what it is now please?

I'm still getting errors which I'm not sure about & the start-up delay is still negative.
![image](https://user-images.githubusercontent.com/8490792/134675914-e67973ce-6f5b-4f55-bfda-2ec10827762c.png)

**Comment by yanj-github** [comment]
Hi @jpiesing 
The changes to start up delay not release?
If you are happy with what I discribe aboove re;
> We can measure the start-up delay between play event and the next detected frame / frame change after the play event no matter which frame number it is. Any frames detected before the play event are ignored. This will prevent any negative start-up delay.
I will add this change to next release.

Regarding to the duration OF measures duration from 2nd detected frame to the last detected frame (no matter what frame number it is) and add one frame duration.
The tolerence is not documented in spec however 10ms is configurable on OF. You are right the duration is not exactly 60 seconds, do you think we should increase the tolerence please?

**Comment by yanj-github** [comment]
Call at 28/09/2012:
- Start up delay: time between play event to the next frame change.
- Duration: 1st detected frame change after the play event to the last detected frame.

**Comment by louaybassbouss** [comment]
As discussed in DPCTF Test Meeting 9/28:
Startup Delay Measurement is defined as the time between calling `play()` and the time of the first frame change after that call. Steps for OF:
* detect QR Code of `play()`  and put current timestamp in `t1`
* detect frame change and put current  timestamp in `t2`
* `startup_delay = t2 - t1`

**Comment by yanj-github** [comment]
@louaybassbouss  Thank you very much this matches what I was proposing here. 
https://github.com/cta-wave/device-observation-framework/issues/27#issuecomment-926609452
@jpiesing 
Spec update required to the start up delay definition.

**Comment by yanj-github** [comment]
As discussed in DPCTF Test Meeting 9/28:
playback duration: mesured from the next frame change after the play() event to the last detected frame. (x to y)
Expected duration: calculated based on what is detected from recording. (y-x +1) * frame rate

- First frame get displayed before play event 
real duration d1= frame 2 to last frame
expected duration d2 = frame 2 to last frame 
d1 and d2 should match within 10ms tolerence

- 3 frames missing at the bignning
real duration d1= frame 4 to last frame
expected duration d2 = frame 4 to last frame 
d1 and d2 should match within 10ms tolerence

- 2 frames missing at the bignning and 3 frames missing at the end
real duration d1= frame 4 to last frame -3
expected duration d2 = frame 4 to last frame -3
d1 and d2 should match within 10ms tolerence

- 2 frames missing at the bignning and 3 frames missing at the end and 10 frames missing in the middle
same as "2 frames missing at the bignning and 3 frames missing at the end"
Any missing middle frames should not be counted

@jpiesing  to make sure I am on the same page, can you confirm this is what you are expecting please?

This required changes in the duration observation from the spec.
Where is says:
The playback duration of the playback matches the **duration of the CMAF Track**, i.e. **TR [k, S] = TR [k, 1] + td[k].**
Also tolerence need to be defined as well if we want to allow 10ms tolerence.

**Comment by cta-source** [comment]
> * detect QR Code of `play()`  and put current timestamp in `t1`

I'm unclear on the meaning of "detect QR code of play()", from the outside "play()" is an API call and the QR code is in a frame observed by the OF--there should be a lag between the two.  If this makes sense to those working inside the OF, that's fine.

Also, what should be the audio version of the two criteria?  Maybe,

- Start up delay: time between play event to the first PN-correlated audio frame.
- Duration: Time from PN-detected start-of-audio to last PN-correlated audio frame

However, I'm not sure how to express these criteria as OF sequences.

**Comment by jpiesing** [comment]
> I'm unclear on the meaning of "detect QR code of play()", from the outside "play()" is an API call and the QR code is in a frame observed by the OF--there should be a lag between the two. If this makes sense to those working inside the OF, that's fine.
> 
> Also, what should be the audio version of the two criteria? Maybe,
> 
>     * Start up delay: time between play event to the first PN-correlated audio frame.
> 
>     * Duration: Time from PN-detected start-of-audio to last PN-correlated audio frame
> 
> 
> However, I'm not sure how to express these criteria as OF sequences.

We have 2 sets of QR codes, one burnt into the video and one drawn by the HTML+JS of the test app. This means the QR code drawn by the test app when play() is called.

**Comment by jpiesing** [comment]
>     * 2 frames missing at the bignning and 3 frames missing at the end and 10 frames missing in the middle
>       same as "2 frames missing at the bignning and 3 frames missing at the end"
>       Any missing middle frames should not be counted

We didn't discuss this one. If an implementation drops a frame then I would expect the timeline to be preserved, i.e. the previous frame to be repeated. Hence the above is **_correct_** - the fact that some frames are missing in the middle is to be ignored when looking at the duration.

**Comment by yanj-github** [comment]
This is fixed now. @jpiesing Feel free to close this issue if you are happy with it please?

**Comment by yanj-github** [comment]
No further comments. Closing this issue now.
