### ISSUE TITLE
Tolerances

### ISSUE THREAD

**Issue by yanj-github** [cta-wave/device-observation-framework#3]
- Every sample S[k,s] shall be rendered and the samples shall be rendered in increasing presentation time order.
There is no tolerance for this observation, therefore 1st frame dropping will flag this observation as failure.

- The playback duration of the playback matches the duration of the CMAF Track, i.e. TR [k, S] = TR [k, 1] + td[k]
Because of the test set up it is required that this observation needs some tolerance. We would like to start with 10 ms.
10 ms is based on camera that it records tests with 120fps. 
This is the tolerance for the test set up, so we would prefer this tolerance not to be user configurable.

**Comment by jpiesing** [comment]
> * very sample S[k,s] shall be rendered and the samples shall be rendered in increasing presentation time order.
>   There is no tolerance for this observation, therefore 1st frame dropping will flag this observation as failure.
> 

I suggest there are 3 tolerances;
1st frame present - default to required but can be disabled in the configuration file
last frame present - default to required but can be disabled in the configuration file
frames between 1st and last (exclusive) - 1 frame can be missing

> * The playback duration of the playback matches the duration of the CMAF Track, i.e. TR [k, S] = TR [k, 1] + td[k]
>   Because of the test set up it is required that this observation needs some tolerance. We would like to start with 10 ms.
>   10 ms is based on camera that it records tests with 120fps.
>   This is the tolerance for the test set up, so we would prefer this tolerance not to be user configurable.

Fine by me.

**Comment by yanj-github** [comment]
Implented. The tolerances are configurable from config.ini file.
