### ISSUE TITLE
Duration check tolerance

### ISSUE THREAD

**Issue by yanj-github** [cta-wave/device-observation-framework#32]
Currently we have duration check tolerance 10ms configured on OF config.ini
What will be the suitable tolerance for duration check please?

We believe 10ms is quite small. I think we need same level of tolerance that we have or current time check. 
What is the suitable tolerance for the duration check?

**Comment by jpiesing** [comment]
> Should we use duration tolerance being a multiple of a frame interval (for video) + a constant.

Yes.

> Same as current time the default being 2 frame intervals + 20ms for video?

I would be inclined to say 0 frame intervals + 20ms.

> If so do we want to use same parameter from test-config.json or keep it seperate from the current time tolerance please?

Different parameters please.

**Comment by yanj-github** [comment]
Allowed tolerance is 20ms and duration frame tolerance is 0.
And this is now configured from TR test-config.json file. 
Tested and result file shows correct value which is 20ms and 0 frame.
