### ISSUE TITLE
improve documentation to add explicit section on how to verify the camera setup is OK

### ISSUE THREAD

**Issue by jpiesing** [cta-wave/device-observation-framework#36]
Everything needed to validate a camera setup is OK is included in the documentation but implicitly. I think there should be an explicit heading "How to verify your camera setup is OK".

**Comment by yanj-github** [comment]
Thanks @jpiesing we suggest user to run a sequetial playback test and check that OF not raising exception about too many camera frames missing. We can add it on the readme are you happy with that please?

**Comment by abdulwahabEDT** [comment]
The document is updated and includes "How to verify the camera setup". @jpiesing can you please check if you are happy with the changes.

**Comment by jpiesing** [comment]
That's what I had in mind.

**Comment by gitwjr** [comment]
Is it possible to create a test file tied to a camera test file that would verify everything works as expected? The ID for both the test file and camera file would have to match. The tester could run both prior to using the camera and know the only variable left was their camera/camera setup.

**Comment by pshorrock** [comment]
@gitwjr to do this a specific 'test' would need to be set up along with the test runner to be able to support this scenario. Fraunhofer might be best placed to put this in place? If so perhaps an issue could be raised on the DPCTF Test Runner repository to support this? The only other thing then needed would be to capture the video used to validate the new test.

**Comment by gitwjr** [comment]
Will move the issue to the DPCTF Deploy git.
