### ISSUE TITLE
Creating New Testcases

### ISSUE THREAD

**Issue by javierbarellano4v** [cta-wave/device-observation-framework#39]
In GitHub, in the Observation Framework README, there is some information how to  support new testcases depending how much they diverge from existing tests.

In terms of the overall workflow to author new testcases, it appears the basic steps to create a new testcase, goes something like the following. I was hoping there was more detailed documentation:

1.	Create the HTML5 file, i.e., template.
2.	Create an entry in a 'new' CSV file.
3.	Run generate-tests.py
4.	Optionally, create a new test folder to generate a dedicated test run without having to generate all testcases. Assuming that new CSV file is utilized.
5.  All of this, is hosted and generated locally as opposed to downloading the generated testcases.

Can someone confirm this flow?

Thanks.

**Comment by yanj-github** [comment]
I would sugguest to raise this issue on dpctf-tests repo as HTML5, csv and generate-tests.py are on dpctf-tests. 
Probabally you will find detailed steps from dpctf-tests documentation https://github.com/cta-wave/dpctf-tests/blob/master/README.md

**Comment by javierbarellano4v** [comment]
I've posted to dpctf-tests and received responses. 

The response has been incorporated into the README.md: https://github.com/cta-wave/dpctf-tests/issues/89

Thank you for your follow-up....
