### ISSUE TITLE
Integrate or link the OF into the Release/Launch Repo 

### ISSUE THREAD

**Issue by gitwjr** [cta-wave/device-observation-framework#44]
@yanj-github @louaybassbouss 
Develop a proposal to the DPCTF on how the OF will be included in the Release/Launch repo. Integrated with the TR, linked, or other?

**Comment by yanj-github** [comment]
Fritz provided a quick guide for setup the TR and OF in the deploy project  https://github.com/cta-wave/dpctf-deploy/blob/master/QUICK_START.md#phase-3-analyse-recording-using-device-observation-framework
We will have a look.

**Comment by yanj-github** [comment]
In general the running OF from inside docker deploy works fine. 
There are some improvment that @FritzHeiden is helping us to make details to follow on issue https://github.com/cta-wave/dpctf-deploy/issues/47

**Comment by yanj-github** [comment]
@gitwjr this is done now, can this be closed?

**Comment by jpiesing** [comment]
> @gitwjr this is done now, can this be closed?

Closing as requested.
