### ISSUE TITLE
Limitation in handling frames for variable fragment durations

### ISSUE THREAD

**Issue by rcottingham** [cta-wave/device-observation-framework#46]
Expected frame numbers are calculated based on the playout parameters and fragment durations for certain tests e.g. splicing. The current master branch of the Observation Framework has a limitation with handling variable fragment durations; an improvement (using MPD timeline) is currently in progress in the DPCAT22 branch. The implementation is deferred for the initial release of the test suite to allow sufficient validation and non-regression testing of the change, and there is also a dependency on a fix for issue  https://github.com/cta-wave/dpctf-tests/issues/109.

**Comment by jpiesing** [comment]
This results in all the splicing tests failing (see https://github.com/cta-wave/device-observation-framework/issues/62) so if this remains deferred, all those tests have to be dropped from the first release. (cc: @gitwjr)

**Comment by yanj-github** [comment]
We have merged audio part in it has addressed the issue, no impact on the scope of release anymore.

**Comment by yanj-github** [comment]
Tested internally and closing this issue.
