### ISSUE TITLE
incorrect number in duration observation?

### ISSUE THREAD

**Issue by jpiesing** [cta-wave/device-observation-framework#52]
> [OF] The playback duration of the playback matches the duration of the CMAF Track, i.e. TR [k, S] = TR [k, 1] + td[k]. FAIL
> Xx01: Playback duration 30156.67ms does not match expected duration 30000.0ms +/- tolerance of 20ms. Allowed tolerance is20ms and duration frame tolerance is 0. Starting missing frame number is 0. Starting frames to take out is 0. Endingmissing frame number is 0.

I believe the start of the 1st frame of Croatia is at recording frame 71882 (09:59.016) and the start of the closing frame of red is at recording frame 75476 (10:28.966).

75476-71882 = 3594 frames at 120Hz = 29.95 seconds.

This is shorter than the actual duration by 2 frames, i.e. 2*40ms, as it doesn't include the first frame and cuts the last frame off without waiting for that frame's own duration.

29.95 seconds + 0.08 = 30.03.

Doing the calculation in time, 88.966-59.016 = 29.95 so there's no difference.

30ms is still outside the tolerance but we need to have a discussion on tolerances.

The difference between 30.156 as printed in the error message and 30.03 is several frames.

If I look at the application transition from playing to finished in frame 75488 of the recording, (75488-71882)/120 + 40ms = 30.45 which is a lot more than 30.156 so it's not that.

What am I missing?

Frame 75488, where player state is changing from playing to finished.

![10_29_066_75488](https://github.com/cta-wave/device-observation-framework/assets/8490792/68170aa2-4ace-4941-b46b-451894f4fa66)

Frame 75476, the first recorded frame of the red frame that marks the end of the sequence.

![10_28_966_75476](https://github.com/cta-wave/device-observation-framework/assets/8490792/27cfb0a6-2a9b-4ba6-8b61-1f6da47f030b)

Frame 75475, a transitional frame between the last frame of the genuine Croatia content and the red frame end-marker.

![10_28_958_75475](https://github.com/cta-wave/device-observation-framework/assets/8490792/f4c4c9ec-4dfe-445b-8241-d0c48c247f9b)

Frame 71883.

![09_59_025_71883](https://github.com/cta-wave/device-observation-framework/assets/8490792/71a020ec-be37-48fc-8e21-61588db2dc88)

Frame 71882. A transitional frame between the green start marker and the genuine Croatia sequence but more Croatia than green.

![09_59_016_71882](https://github.com/cta-wave/device-observation-framework/assets/8490792/2e05d17c-2bb0-49ff-9f29-7d66f6323e43)

Another transitional frame but more green than Croatia.

![09_59_008_71881](https://github.com/cta-wave/device-observation-framework/assets/8490792/48f0e965-1dc2-48ae-8b64-b648da12ed83)

**Comment by yanj-github** [comment]
@jpiesing Please see the algorithm documented in detail here: https://github.com/cta-wave/device-observation-framework/wiki/Observation-Algorithms#the-playback-duration-of-the-playback-matches-expected-duration
Expected duration is being calculated from 1st detection of frame 1 till the 1st detection of last frame + one frame duration.
If the frame 1 is preloaded before the playback start it will measure from the next frame change, but it seems not in your case. 
Can you please check if the reported duration is correct if you measure from frame number 1 instead of from 2 please?

If you run the OF enable debug log you will see full list of qr code that is detected by OF. 
"--log <info|debug>" default is info. It would be helpful if you can attach the csv file contains full detected qr codes in session log folder.

**Comment by jpiesing** [comment]
From the text you quote ....

> Some devices display frame 1 before the play event.

This particular device shows "“s: playing; a: play; ct:0;” at frame 71801 and the first frame of video starts showing at frame 71861 although the QR code is dim and may not be detected until frame 71862.

> Measurement starts from a detected frame after the play().

In this case, the first detected frame after the play (i.e. the standard green frame) is held from frame 71862 to frames 71881/2. Frame 71881 is green with a trace of the first non-green frame beginning to be visible. Frame 71882 is the converse with a green cast. Frame 71883 has no green cast.

If the OF starts counting the duration from frame 71862 then this is wrong.

> There are some devices hold on to the last frame until the next test is loaded.

Yes. The red last frame is visible from frame 75476 onwards until the next test starts.

> Actual playback duration is measured from the first detection time of the first detected frame till the first detection time of the last detected frame. The last frame duration is added to account for the whole duration.

If I interpret this literally, this would be from frame 71862 and would erroneously include almost 20 frames of green.

IMHO If the OF is excluding the first frame being held when this happens before the play then it should also exclude the first frame being held after the play.

**Comment by yanj-github** [comment]
> IMHO If the OF is excluding the first frame being held when this happens before the play then it should also exclude the first frame being held after the play.

@jpiesing just wanted to rule out this is not a networking delay. Is this test pulling content online or the local test please? I have seen same problem on out test device that longer buffering delay on frame 1 while it is pulling the content online. 

What we have agreed with the group before is that OF only excluding the first frame being held when load until play. If we all agreed to exclude the 1st frame regardlessly (before play or after play) this would be a change request to OF.

**Comment by jpiesing** [comment]
8.2.5.1 says this;

![image](https://github.com/cta-wave/device-observation-framework/assets/8490792/d4cb52ca-1282-4097-bb8e-e3fad7482fac)

I believe that is correct where "playback" is defined as the observed media timeline advancing. You only know the media timeline is advancing when you see the second frame.

**Comment by jpiesing** [comment]
Proposal (edited) from other issue;

We should measure the time from when the second detected frame is first detected to when the last detected frame is first detected. We then need to correct for the difference between this and the CMAF duration which will be up to 2 frame durations of the encoded video.

Discussion
- What if the first frames are missing?
- Measure duration from 2nd detected frame to last detected frame
- Other tests will fail if frames are never shown
- Compensating for durations of first and detected frame and last detected frame will need to compensate for possibly differing frame rates.

**Comment by yanj-github** [comment]
Duration now changed to measure from 2nd detected frame to the 1st detection of the last detected frame and add first and last detected frame duration to correct the difference. 2nd detected frame and last detected frame may not match the 2nd and last expected frame. e.g: when frame 1 and 2 are missing the measurement starts from frame number 4 (this is 2nd detected frame)
When there are missing frames at either end the expected duration is corrected for the difference of missing frame. 

The changes have been commited to the main branch.

**Comment by yanj-github** [comment]
@jpiesing feel free to close issue if you are happy with your test result. Thanks

**Comment by jpiesing** [comment]
I am happy with the changes that exclude hardware decoder initialisation time from duration.
