### ISSUE TITLE
running the OF without access to the correct test runner

### ISSUE THREAD

**Issue by jpiesing** [cta-wave/device-observation-framework#53]
The documentation says that the OF must be run with access to the test runner used to run the test in the beginning - so that the OF can insert it's result into the results from the original test execution.

This is not always the case, e.g. if someone gets a recording of a test run to analyse from a colleague, potentially in a different site.

It would be good to be able to run the OF without a test runner or at least without access to the original test runner used to run the test in the first place. 

If this can be done already then please add something to README.md explaining that it can be done and how it can be done.

**Comment by yanj-github** [comment]
This is not part of the requirement, however, we have done something already to help OF testing and debuging which we are happy to share. I will create a document in wiki and will add a link to README.

**Comment by yanj-github** [comment]
@jpiesing I have started to document this on https://github.com/cta-wave/device-observation-framework/wiki/Debug-Observation-Framework
It is not easy to understand connections between test runner configuration file and OF it might cause confusion, we recommend using it only for debugging. And wanted to mention that if the recording taken then test runner configuration file changed it will cause the OF unable to process to the end or giving different result. It is important to use RIGHT configuration file.
Feel free to let me know if you have further comments and feedbacks.

**Comment by jpiesing** [comment]
@yanj-github On the URL above, it gives the following example;

> python observation_framework.py --input <recording_file> --mode debug --log debug

When I do basically that, get the following;

> $ python3 observation_framework.py --input ~/Downloads/20230714_143525.Phillips.mp4 --mode debug --log debug
> usage: observation_framework.py [-h] [--input INPUT] [--log {debug,info}]
>                               [--scan {general,intensive}]
> observation_framework.py: error: unrecognized arguments: --mode debug

Is '--mode debug' correct? Is it only on a branch?

**Comment by yanj-github** [comment]
Can this be closed now please? @jpiesing

**Comment by jpiesing** [comment]
I've used this extensively and it works.
