### ISSUE TITLE
start-up delay observation not run for 9.2/3/4

### ISSUE THREAD

**Issue by jpiesing** [cta-wave/device-observation-framework#55]
The start-up delay observation was not run for the 3 tests including both video and audio,

- random-access-of-a-wave-presentation__t1.html
- regular-playback-of-a-cmaf-presentation__t1_at1.html 
- splicing-of-wave-program-with-baseline-constraints__splice_main_splice_ad.html 

Testing initialisation of both video and audio decoders is more relevant than testing initialisation of video without audio or vice-versa.

In the DPCTF spec, 9.?.5.2/3 contain references to 8.2.5.2/3 just like the 8.?.5.2/3.

**Comment by yanj-github** [comment]
@jpiesing We have merged audio part in it should includes start-up delay observation for 9.2/3/4.
