### ISSUE TITLE
new value for maximum permitted start-up delay

### ISSUE THREAD

**Issue by jpiesing** [cta-wave/device-observation-framework#56]
Currently the maximum permitted start-up delay is 120ms.
This needs to be reviewed against the results from the plugfest.
Initial results from @FritzHeiden suggest something in the region of 500-600-700 is average across most (but not all) devices but the worst case is a lot larger. More analysis is needed to see if the same test is the worst case across devices from multiple manufacturers. If this would be the case then the test content and the test would need to be investigated to see if they are correct. If they are correct then that one test may need a tolerance >1.2s.

**Comment by yanj-github** [comment]
All the tolerance parameters are set on doctf-tests not on OF. I think it would be fine to set different value for a test but which need to be confirmed by @louaybassbouss
