### ISSUE TITLE
debugging failure due to "[OF] The presented sample matches the one reported by the currentTime value within the tolerance of the sample dur..."

### ISSUE THREAD

**Issue by jpiesing** [cta-wave/device-observation-framework#57]
I'm trying to debug the last item in this failure message ..

![image](https://github.com/cta-wave/device-observation-framework/assets/8490792/0d455403-dd41-4c97-9a0a-06922d71b3fe)

Examining the video, "ct: 7.93" starts on frame #4125 in the recording (frame #403 in the encoded video) and continues to frame #4143 (frame #406/#407 in the encoded video). frame #4144 in the recording shows "a: representation_change; ct: 8.009;".

How should I investigate this further? Which frame of the recording is this referring to?

@yanj-github You have this recording.

**Comment by yanj-github** [comment]
@jpiesing Which test is this, can I have test code please? You can run OF with --log debug to enable additional log which will create a csv file contains all QR code detected and on which recording frame as well.

**Comment by jpiesing** [comment]
> "ct: 7.93" starts on frame #4125 in the recording - you also need to read "d" value as well. The current time QR code has delay in generating so the actual detected frame is earlier then what is presented it should be take into account of delay as well.

So how do I determine where to look in the recording? (As I said, you have this recording).

**Comment by gitwjr** [comment]
Hi Jon,

I asked this question when I was running tests. I wanted a known “good” recording to test the OF install separately to narrow down where to look for errors. I was told the OF had to use the recording generated at the time  the TR test results were generated due to an ID the TR generates when run. If the recording ID didn’t match the Test run results passed to the OF it wouldn’t run. I don’t know if that has changed. It seemed to me that there must be a way to “force” the ID into the OF prior to run time.

I seem to remember there was an email or Git comment that there was a way to do it now. I assume that is why Yan/Resillion keeps asking for the recordings from runs that are reported to have failed but it could be they have tools that can examine the recordings without having to run the OF within the Suite.

**Comment by yanj-github** [comment]
From the debugging log I can see that the 7.930 current time is reported at recording frame 1761 (14.675s), delay is reported on next status QR code. The next status report is current time 8.009 with delay 35ms.
So actual 7.930 current time should have been reported at 14675-35=14640ms
From recording frame 1752 (14600ms) to 1757 (14642ms) detected frames and media time is as follows.

recording frame| ID | media time| frame number| frame rate
-- | -- | -- | -- | --
1752 | L2 | 8020 | 401 | 50
1753 | L2 | 8020 | 401 | 50
1754 | L2 | 8040 | 402 | 50
1754 | L2 | 8020 | 401 | 50
1755 | L2 | 8020 | 401 | 50
1755 | L2 | 8040 | 402 | 50
1756 | L2 | 8040 | 402 | 50
1757 | L2 | 8040 | 402 | 50

Is makes the diff 8020-7930=90ms which is more than tolerance of 2 frames + 20ms = 1000/50 + 20 = 80ms

**Comment by yanj-github** [comment]
@jpiesing and @louaybassbouss, I found that the action is "representation_change" from currenTime = 8.009 till the end, and current Time match observation not done from currenTime = 8.009 onwards. Becasue we only check currentTime match when status is "playing" and action is "play". 
I remembe that "representation_change" is a action status that recently added. 
It would  be easy for us to add current Time match to "representation_change" as well but I just wanted to confirm this is not a bug in status report beforehand please?
I was expecting action to be changed from "representation_change" to "play"?

**Comment by yanj-github** [comment]
Now OF carry on with measuring the current time match when action = "representation_change"  as well. The changes are commited to the main branch.

**Comment by jpiesing** [comment]
> Now OF carry on with measuring the current time match when action = "representation_change" as well. The changes are commited to the main branch.

I'm running the main branch of the OF against the Philips recording right now.

**Comment by yanj-github** [comment]
@jpiesing anything for us left to do with this issue please?
