### ISSUE TITLE
required version of opencv-python not available

### ISSUE THREAD

**Issue by jpiesing** [cta-wave/device-observation-framework#58]
The OF won't install on my new laptop.

> ERROR: Could not find a version that satisfies the requirement opencv-python==4.5.2.52 (from versions: 3.4.0.14, 3.4.10.37, 3.4.11.39, 3.4.11.41, 3.4.11.43, 3.4.11.45, 3.4.13.47, 3.4.15.55, 3.4.16.57, 3.4.16.59, 3.4.17.61, 3.4.17.63, 3.4.18.65, 4.3.0.38, 4.4.0.40, 4.4.0.42, 4.4.0.44, 4.4.0.46, 4.5.1.48, 4.5.3.56, 4.5.4.58, 4.5.4.60, 4.5.5.62, 4.5.5.64, 4.6.0.66, 4.7.0.68, 4.7.0.72, 4.8.0.74, 4.8.0.76)
> ERROR: No matching distribution found for opencv-python==4.5.2.52

The OS is ubuntu jammy.

> $ uname -a
> Linux rocinante 6.2.0-33-generic #33~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Thu Sep  7 10:33:52 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

If I do 'pip install opencv-python' without forcing a version, I get 4.8.0.76.

**Comment by jpiesing** [comment]
> @jpiesing what is your python and pip version please? I think there are no wheels for that release for your python version.

Python 3.10.12
pip 23.2.1

**Comment by jpiesing** [comment]
From https://packages.ubuntu.com/jammy/i386/python3

![image](https://github.com/cta-wave/device-observation-framework/assets/8490792/e8cbea4f-06c5-453b-b794-978fe2a65e03)

This is the default version of python for an Ubuntu LTS release so requiring an OpenCV version that's not supported is annoying.

**Comment by yanj-github** [comment]
@jpiesing Is it possible to downgrade python to use older version which supports opencv-python==4.5.2.52 please?

**Comment by jpiesing** [comment]
@yanj-github Please consider enhancing install.sh to generate a warning if the python version is too high.

I will create a new issue (deferred) to permit use of a higher version of python.

**Comment by yanj-github** [comment]
FYI: We are looking at set up OF within docker and deploy together with test runner. https://github.com/cta-wave/device-observation-framework/issues/60 Once OF can be running inside docker, versioning wont be an issue anymore.

**Comment by jpiesing** [comment]
If the remaining issues in https://github.com/cta-wave/dpctf-deploy/issues/47 are resolved then this issue can be closed with no further action.

**Comment by jpiesing** [comment]
It may be worth updating the documentation to mention that a python virtual environment can be used to install python3.9 even if the native python version of the distribution is 3.10 or greater. That's what I've done.

**Comment by gitwjr** [comment]
Handled in Deploy #47. Close.
