### ISSUE TITLE
no mention of config.ini and editing it if test runner is identified by IP address

### ISSUE THREAD

**Issue by jpiesing** [cta-wave/device-observation-framework#6]
It's optional to setup DNS so that the test runner is at http://web-platform.test.

The instructions for the test runner and the deploy project don't mention this - it's sort-of expected that the docker image will be running on an arbitrary machine that may only be identified by an IP address or indeed localhost.

I think the documentation should mention at least editing config.ini to replace web-platform.test with either an IP address or with localhost.

**Comment by yanj-github** [comment]
Thanks @jpiesing we will update readme file to include this.

**Comment by jpiesing** [comment]
I just edited config.ini to replace web-platform.test with localhost since the observation framework is running on the same machine as the test runner docker image.

**Comment by yanj-github** [comment]
Duplicated to https://github.com/cta-wave/device-observation-framework/issues/14

**Comment by yanj-github** [comment]
@jpiesing Can we close this?

**Comment by jpiesing** [comment]
OK.
