### ISSUE TITLE
possible regression on currentTime vs QR code time comparison

### ISSUE THREAD

**Issue by jpiesing** [cta-wave/device-observation-framework#61]
When the OF was run on a recording in July, there were only a few errors from the comparison between currentTime and time from the QR codes. As an example, here is sequential track playback T1.

![image](https://github.com/cta-wave/device-observation-framework/assets/8490792/e63135c7-957f-485e-9e3a-09e127ac076c)

Running the current version of the OF, there's many more errors.

![image](https://github.com/cta-wave/device-observation-framework/assets/8490792/08584c0e-e037-46ff-aea3-160c9bdcdd75)

Is this a regression?

Although I'm using sequential track playback t1 as an example, this failure appears to be pervasive.

**Comment by yanj-github** [comment]
@jpiesing I got recording can you let me know which test is this please? I can have a look.

**Comment by jpiesing** [comment]
> @jpiesing I got recording can you let me know which test is this please? I can have a look.

I've not checked exhaustively but it's in every single test I've looked at. The specific example above is 
/cfhd_12.5_25_50-local/sequential-track-playback__t1.html which is where I normally start as it's just about the simplest possible test.

**Comment by yanj-github** [comment]
Ah @jpiesing can you check your test-config.json file I can see your result saying " Allowed tolerance is 0 frames, 20ms."

**Comment by yanj-github** [comment]
@jpiesing if there is nothing to be fixed on OF feel free to close the issue. Thanks

**Comment by jpiesing** [comment]
Closing.
