### ISSUE TITLE
frame rate of recording may (not) be exactly 120fps

### ISSUE THREAD

**Issue by jpiesing** [cta-wave/device-observation-framework#64]
I have a new recording from @FritzHeiden (20231010) which my video editor thinks is 118.5 fps and not 120 fps. If I use ffprobe on this, I get the following;

Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '20231010_145113_dpctf_a5097bcc-676b-11ee-bbef-0242ac110003.mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: isommp42
    creation_time   : 2023-10-10T13:11:16.000000Z
    com.android.version: 13
    com.android.capture.fps: 120.000000
  Duration: 00:20:03.27, start: 0.000000, bitrate: 45264 kb/s
  Stream #0:0(eng): Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, bt709), 1920x1080, 44999 kb/s, 118.54 fps, 120 tbr, 90k tbn, 180k tbc (default)
    Metadata:
      creation_time   : 2023-10-10T13:11:16.000000Z
      handler_name    : VideoHandle
      vendor_id       : [0][0][0][0]
  Stream #0:1(eng): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 256 kb/s (default)
    Metadata:
      creation_time   : 2023-10-10T13:11:16.000000Z
      handler_name    : SoundHandle
      vendor_id       : [0][0][0][0]

If I look at the 2023-07-14 recording, that claims to be 120 fps.

Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '2023-0714-philips-tv-recording_assets/20230714_143525.Phillips_dpctf_fde3abd2-2242-11ee-87fa-0242ac110003.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf57.83.100
    location-eng    : +00.0000+000.0000/
    location        : +00.0000+000.0000/
  Duration: 00:30:01.28, start: 0.000000, bitrate: 7145 kb/s
  Stream #0:0(eng): Video: h264 (Main) (avc1 / 0x31637661), yuv420p, 1920x1080 [SAR 1:1 DAR 16:9], 7141 kb/s, 120 fps, 120 tbr, 15360 tbn, 240 tbc (default)
    Metadata:
      handler_name    : VideoHandler
      vendor_id       : [0][0][0][0]

For the 20231010 recording, what framerate will the OF use, 118.5fps or 120fps?

A lot of tests that can be persuaded to pass with the 20230714 recording fail on the 20231010 one.

I wonder if the OF is working off 118.5 when it should be working off 120 or vice-versa.

**Comment by yanj-github** [comment]
@jpiesing I am using the camera that records at 120000/1001 fps it works with OF. The OF is taking the actual recording frame rate from input file which we believe it should work with any frame rates. If the testing content is in hight frame rate (60fps) 118.5fps might be able able to capture as well as it compared with 120fps, we recommend twice the frame rate of the testing contents if possible.

**Comment by yanj-github** [comment]
Tested with the recording and OF processing well and give correct result to different recording frame rate 118.5fps. OF reading correct recording frame rate from the input file and use right frame rate when calculating.
Compare with 120fps:
- Capture less frames, might cause missing detection of frames for high frame rate content (60fps - we suggest to capturing twice the rate)
- Capture QR codes in longer intervals, also means less frequent capture of status QR code change and mezzanine QR codes. Might impact on current time check or the duration match check.

The impact would be trivial, because the differences between 120fps and 118.5fps is just 0.1ms.

**Comment by jpiesing** [comment]
Closing.
