### ISSUE TITLE
Linking additional documentation on debugging observation failures when failures are encountered

### ISSUE THREAD

**Issue by gitwjr** [cta-wave/device-observation-framework#66]
A separate document https://github.com/cta-wave/device-observation-framework/wiki/Debugging-Observation-Failures) is required to describe how to debug observation failures. see Issue #51. It would be useful to include a link to the document when such failures occur to guide the test engineer. A discussion as to how this can be done is needed.  This issue is deferred to the next release

**Comment by jpiesing** [comment]
I'm unclear where it is proposed to include the link to the additional document on debugging. Is it proposed to put it in the OF readme? In the QUICKSTART? A one line entry in QUICKSTART may be most appropriate.

**Comment by gitwjr** [comment]
I agree QuickStart is needed since that is where they will be working from. There are also helpful hints on the windows_wsl.md page which would be useful in QS. https://github.com/cta-wave/dpctf-deploy/blob/master/WINDOWS_WSL.md 

It might be helpful for troubleshooting/hints (oro links) on the README page and the OF Guide.

**Comment by yanj-github** [comment]
The link is added to OF readme in section troubleshooting. @FritzHeiden can you add link to Troubleshooting from QUICK start please?

**Comment by jpiesing** [comment]
@FritzHeiden Please can you add a new section at the end of deploy / README.md which references this new text. Perhaps something like the following;

Debugging

If the observation framework reports errors and/or that the device has failed, some information on the analysis and debugging of errors can be found at https://github.com/cta-wave/device-observation-framework/wiki/Debugging-Observation-Failures

**Comment by FritzHeiden** [comment]
Done https://github.com/cta-wave/dpctf-deploy/pull/71

**Comment by jpiesing** [comment]
Looks good to me.
