### ISSUE TITLE
improving error messages when dependencies are not met / explicitly checking for them

### ISSUE THREAD

**Issue by jpiesing** [cta-wave/device-observation-framework#68]
It seems that there's little or no explicit checking that OF dependencies are met, e.g. presence of files, ability to contact test runner, and so on. This results in any absence being reported via python exceptions which is not user-friendly.

Explicit up-front checks that the most critical dependencies are met should be added with user-friendly error messages if they are not met.

I've listed this as a blocker for non-technical reasons. There is a perception that WAVE is hard to install and run, I think not fixing this risks re-inforcing that perception when people are trying to install wave and having problems.

**Comment by yanj-github** [comment]
Hi @jpiesing and @gitwjr this is now completed and new changes are available on master. 
Error messages are improved for when test runner connection not met and warning message when corrupted frames found.

**Comment by jpiesing** [comment]
Checked and looks good.
