### ISSUE TITLE
refactor documentation to separate docker, non-docker and common

### ISSUE THREAD

**Issue by jpiesing** [cta-wave/device-observation-framework#69]
The current README for the OF includes 1) installation / setup instructions (which are irrelevant and confusing if the OF was installed by docker) and 2) usage instructions which are relevant however the OF was installed.

It needs to be clearer what text is specific to one particular way of installing the OF and what is independent of how the OF was installed.

At least the non-docker setup text needs to be clearly identified as not being relevant to a large audience.

If we expect most people will use the OF via docker then perhaps the best approach would be to move the non-docker Setup / Installation into a separate file. The README could then include a very short piece referencing that file for non-docker installations and the QUICK_START for docker installations but otherwise only include material independent of how the installation was done.

**Comment by gitwjr** [comment]
At what point in the Quick Start Guide is the OF built? When I installed using current Quick Start (after deleting the TR and OF folders/contents and deleting the Docker containers and images) the OF was not installed. No "device-observation-framework-main" folder was created when I ran ./build-dof.sh (dof image was created) and therefore none of the programs, subfolders, etc., or place to add the observation-config.ini. I had to follow OF guide to add the OF.

**Comment by gitwjr** [comment]
It appears the new QS adds the steps to build the OF. Much clearer now. I will try to rebuild today using new QS Guide.

**Comment by yanj-github** [comment]
@jpiesing and @gitwjr this is completed.

**Comment by jpiesing** [comment]
@yanj-github It's not completed as I imagined it. There's still a lot of material in README.md that is not relevant to someone who has followed QUICK_START.md. I envisaged that material being moved into a new file so someone following QUICK_START.md would not find anything potentially confusing.

**Comment by yanj-github** [comment]
@jpiesing updated as requested can you check again please?

**Comment by jpiesing** [comment]
Thank you for that. I think it will be much less confusing for people coming from QUICK_START.md. I just have two small editorial comments.

![image](https://github.com/cta-wave/device-observation-framework/assets/8490792/c10cc271-4ecf-43e0-861e-1cbcabfaa53e)

1. "Running the Device Observation Framework" should be promoted to being the same level of heading as "Setting up the Device Observation Framework".
2. The two sub-headings, 'Setting up inside Docker container' and 'Or setting up without Docker' could perhaps be reduced to two bulleted items unless they happen to be linked from outside.

**Comment by rcottingham** [comment]
Thanks for the feedback Jon - editorial updates made as you suggested.

**Comment by rcottingham** [comment]
Done, thanks.

**Comment by jpiesing** [comment]
Looks good to me.
