### ISSUE TITLE
dropped frames from middle may pass threshold but fail on duration

### ISSUE THREAD

**Issue by jpiesing** [cta-wave/device-observation-framework#74]
There is a threshold of 10 for dropped frames in the middle of a sequence for the observation

"[OF] Every video frame S[k,s] shall be rendered and the video frames shall be rendered in increasing presentation time order."

Some implementations drop frames and do not preserve the media timeline resulting in failure of the duration observation.

If it's possible, a failure of the duration observation when 'every video frame' also fails should be resulted as something other than 'FAIL', particularly if the duration would pass if adjusted for the number of frames dropped.

**Comment by yanj-github** [comment]
IF I remember correctly, 10 missing frame tolerance was introduced to overcome false negatives due to recording not clear enough to detect the every frames. Either cause by the recording device not robust enough or the playback screen is too small (on the phone) with low resolution content. 
I think we need more thinking on this. But my 1st impression is that when we having new observation https://github.com/cta-wave/device-playback-task-force/issues/119 added this will be clearer.

**Comment by yanj-github** [comment]
@FritzHeiden and @louaybassbouss does test runner accept any other result status than "PASS" or "FAIL"?
If this is purely a string can I report "WARNING"?

**Comment by jpiesing** [comment]
> IF I remember correctly, 10 missing frame tolerance was introduced to overcome false negatives due to recording not clear enough to detect the every frames. Either cause by the recording device not robust enough or the playback screen is too small (on the phone) with low resolution content. I think we need more thinking on this. But my 1st impression is that when we having new observation [cta-wave/device-playback-task-force#119](https://github.com/cta-wave/device-playback-task-force/issues/119) added this will be clearer.

From recordings I've seen, there are genuine missing frames and not just false negatives.

**Comment by yanj-github** [comment]
Regarding to every frame rendered: 
From spec is says "Every video frame S[k,s] shall be rendered" it sound to me that we should not allow any mid missing frames. What do you think @jpiesing?

For the duration check: we can pass the observation if adjusted for the number of frames dropped in the middle. Which then require spec wording to be changed as follows:
The playback duration shall match the duration of the CMAF Track – i.e., TR[k,S] = TR[k,1] + td[k] taking into account:
•	**Missing frames,**
•	Potential start frames being rendered before playback,
•	Frozen last frame after the playback ended.

**Comment by jpiesing** [comment]
There are two possible variations on missing frames.
- Missing frames where the media timeline is preserved, i.e. the following frames are shown at the correct time, which means the frame before the missing one is prolonged
- Missing frames where the media timeline is not preserved and a frame duration is just dropped from the media timeline.

The first of these is significantly less wrong than the second, particularly for live.

**Comment by yanj-github** [comment]
>Missing frames where the media timeline is not preserved and a frame duration is just dropped from the media timeline.

We will change the OF to make the duration observation also PASS with additional explanation in message.

**Comment by jpiesing** [comment]
> > Missing frames where the media timeline is not preserved and a frame duration is just dropped from the media timeline.
> 
> We will change the OF to make the duration observation also PASS with additional explanation in message.

For which of the variations in my earlier comment or both?

**Comment by yanj-github** [comment]
> > > Missing frames where the media timeline is not preserved and a frame duration is just dropped from the media timeline.
> > 
> > 
> > We will change the OF to make the duration observation also PASS with additional explanation in message.
> 
> For which of the variations in my earlier comment or both?

- Missing frames where the media timeline is preserved, i.e. the following frames are shown at the correct time, which means the frame before the missing one is prolonged

This is already a PASS from OF at the moment.

- Missing frames where the media timeline is not preserved and a frame duration is just dropped from the media timeline.

We will PASS this as well and add additional message in result.
e.g:
_"status": "PASS",
"message": "Playback duration is 59733.33ms, expected track duration is 59980.0ms. Detected duration is different by 246.67ms. **The media timeline is not preserved for mid missing frames and 200ms duration is dropped from the media timeline.** Allowed tolerance is 50ms and duration frame tolerance is 0. Starting missing frame number is 0. Ending missing frame number is 1.",
"name": "[OF] Video: The playback duration shall match the duration of the CMAF Track"_

**Comment by jpiesing** [comment]
> It would be easier to do replace in word document.

I agree that it would be a lot easier.

**Comment by jpiesing** [comment]
> Changes now committed to main.

Do you believe this can be closed when https://github.com/cta-wave/device-playback-task-force/issues/127 is approved in DPCTF?

**Comment by yanj-github** [comment]
@jpiesing yes, if we agree to change "Missing starting and ending frames" with "Missing frames".

**Comment by yanj-github** [comment]
@jpiesing This issue can be closed now, feel free to close this issue when you happy with the change please.
