### ISSUE TITLE
error in calculating duration for random-access-from-one-place-in-a-stream-to-a-different-place-in-the-same-stream__t2

### ISSUE THREAD

**Issue by jpiesing** [cta-wave/device-observation-framework#75]
As described in https://github.com/cta-wave/dpctf-tests/issues/154 , 7 of 8 tests did not pass.

Here is an example error message from TV 7.

> FAIL: Playback duration 31471.67ms does not match expected duration 20000.0ms +/- tolerance of 50ms. Detected duration is different by 11471.67ms. Allowed tolerance is 50ms and duration frame tolerance is 0. Starting missing frame number is 0. Ending missing frame number is 0. Additional allowed random_access_from_tolerance is 200ms.

Here is an analysis of the recording of TV 7.

![image](https://github.com/cta-wave/device-observation-framework/assets/8490792/406f0141-2cc4-4c9b-b06e-880a8c9ccbb2)

Based on this analysis, I believe this should be a pass therefore there's something wrong in the calculation.

Looking at the DPCTF spec, the definition of the duration calculation is as follows.

![image](https://github.com/cta-wave/device-observation-framework/assets/8490792/f8eec112-bc1e-4b0b-be15-1e308897ac1f)

It looks like the duration calculation is including the period while the seek is happening as measured in the timeline of the recording, i.e. the period between frames 76667 and 75315 in the above example. This is clearly wrong. The duration calculation needs to take account of the part of the original content that's skipped but as measured in the timeline of the encoded content.

**Comment by yanj-github** [comment]
Hi @jpiesing Do we need to take into account frames holding while seeking please? I think OF added delay in total duration calculation but I noticed at the gap the last frame presented longer.
1)	The playback duration shall match the duration of the CMAF Track, i.e. TR[k,S] = TR[k,1] + td[k] taking into account:
- Missing starting and ending frames.
- Potential start frames being rendered before playback.
- Frozen last frame after the playback ended.
- Skipped frames between random_access_from and random_access_to
**- Frozen last frame and start frame while seek is happening**

**Comment by jpiesing** [comment]
> Hi @jpiesing Do we need to take into account frames holding while seeking please? I think OF added delay in total duration calculation but I noticed at the gap the last frame presented longer.
> 
> 1. The playback duration shall match the duration of the CMAF Track, i.e. TR[k,S] = TR[k,1] + td[k] taking into account:
> 
> * Missing starting and ending frames.
> * Potential start frames being rendered before playback.
> * Frozen last frame after the playback ended.
> * Skipped frames between random_access_from and random_access_to
>   **- Frozen last frame and start frame while seek is happening**

This is similar to the proposal in https://github.com/cta-wave/device-playback-task-force/issues/122.

**Comment by yanj-github** [comment]
Changes now committed to main.

**Comment by jpiesing** [comment]
Closing as seems to work.
