### ISSUE TITLE
easy support for recordings divided into multiple files by the camera

### ISSUE THREAD

**Issue by jpiesing** [cta-wave/device-observation-framework#8]
I had a quick look at the code but couldn't work out if this was already supported.
If it is already supported then it's just a documentation issue, if not then please consider supporting it.

Some cameras divide recordings into multiple files, e.g. once the file exceeds a certain size.
It would be helpful if it was possible to specify multiple inputs to the observation framework and have it step through them as if they were a single file.

**Comment by yanj-github** [comment]
Thanks Jon, yes we were aware of this use case. This is on our todo list already which will be included on next release. Current code does not support this yet.

**Comment by yanj-github** [comment]
This is supported alreay. @jpiesing Can we close this?

**Comment by jpiesing** [comment]
@yanj-github I wanted to test it but yes, we can close it & re-open if there's a bug.
