### ISSUE TITLE
Observation missing for  low-latency-short-buffer-playback

### ISSUE THREAD

**Issue by yanj-github** [cta-wave/device-observation-framework#82]
Observation: The video element transitions into playing state before the waiting_duration, timeout elapses.

Waiting for error event to be added by test runner then OF should catch it from status QR code.

**Comment by FritzHeiden** [comment]
Isn't this the intended behavior? The test throws an exception if the video does not play within the waiting duration:

![image](https://github.com/cta-wave/device-observation-framework/assets/9076000/1b3a3cc7-e7ab-4d87-8880-b25d8e0974d6)

**Comment by yanj-github** [comment]
@FritzHeiden the spec updated and please refer to latest draft.


8.22.4	Stimulus
•	Append the CMAF Header CH[k] to the Source Buffer.
•	Set SourceBuffer.timestampOffset to -tf[k,1].
•	Load and append the CMAF chunks until the buffer reaches a duration equal to or higher than maximum_forward_buffer.
•	Start a timeout with a duration equal to waiting_duration.
•	In case the video element transitions into the playing state before the timeout elapses:
Append the rest of the CMAF chunks of CMAF track k.
Otherwise terminate the test.

8.22.5	Required Observations
8.22.5.1	General
**1)	The video element transitions into playing state before the waiting_duration, timeout elapses.**

If test runner already terminates the test with error message. OF wont make any observation if there is error. It seems like that the highlighted observation already made on test runner. @FritzHeiden can you confirm please?

@jpiesing if this observation already made on test runner, no changes required to OF. Are you happy this stays in "Required Observations" section or move back to the "Stimulus"? "Required Observations" section normally contains observations made by the OF.

**Comment by FritzHeiden** [comment]
@yanj-github Even with the excerpt from the latest draft, this stays the same semantically. 

I double checked this: TR correctly throws the error, however, it was not explicitly listed in the result. I fixed this with https://github.com/cta-wave/dpctf-tests/pull/182. It looks like this now:

![image](https://github.com/cta-wave/device-observation-framework/assets/9076000/0762ef52-eff2-4118-a45a-ce7a77504ca9)

**Comment by yanj-github** [comment]
Thanks @FritzHeiden as this observation made on test run I will close this issue. 
No OF changes required.
