### ISSUE TITLE
How to record audio on devices where no 3.5mm audio output

### ISSUE THREAD

**Issue by yanj-github** [cta-wave/device-observation-framework#85]
Test and document "How to record audio on devices where no 3.5mm audio output".
Possible solutions:
- via SP DIP
- via HDMI ARC

**Comment by yanj-github** [comment]
- Tested and HDMI ARC can be used. It has same level of PASS/FAIL compared with 3.5mm audio. No delays noticed on HDMI ARC.
- SP DIP added some noise to the signal and which caused the audio observation to fail. Not suggested.
![image](https://github.com/cta-wave/device-observation-framework/assets/59022223/239107ec-b70a-4456-9562-f04a69317039)

**Comment by jpiesing** [comment]
@Nicholas-fr

**Comment by nicholas-fr** [comment]
Regarding HDMI ARC and S/PDIF out (TOSLINK optical or RCA/coax), aside from some limited exceptions, they usually carry the same digital audio signal, so it should be possible to use either. 

The DUT should be configured to ensure that:
- The digital audio out is uncompressed stereo (not bitstream).
- The digital audio out is configured to be in sync with video (normally the default).
- The correct audio output is selected (ARC and S/PDIF outputs can be mutually exclusive on some devices).
- If using ARC, both ARC and HDMI CEC functionality should be enabled, as CEC is required to initiate ARC.

Any transients/noise in the recording suggest issues with the setup, but should not be an issue inherent to S/PDIF.

It may be useful to add some of these details to the document.

**Comment by yanj-github** [comment]
Thanks @nicholas-fr for the comments. Your suggestions are added to the document. As there is no more comments I am closing this issue.
