### ISSUE TITLE
log information appears to go into a single log file, please use one per session

### ISSUE THREAD

**Issue by jpiesing** [cta-wave/device-observation-framework#9]
The log information from multiple runs of the observation framework all appears to go into a single log file.
Please consider using a new log file for each session with the session ID in the filename.

**Comment by yanj-github** [comment]
OF wont be able to get session ID until it detected the pre-test QR code. There are some logs before that. 
We can seperate the general event logs and session related logs into seperate log files.

**Comment by jpiesing** [comment]
> OF wont be able to get session ID until it detected the pre-test QR code. There are some logs before that.
> We can seperate the general event logs and session related logs into seperate log files.

If that's the best that can be done then OK. I really do think it's useful to have a log for each session with the session ID in the file name.

**Comment by jpiesing** [comment]
OK.
